import type { Note } from "./notes-data";

export const eternalSunshineNote: Note = {
  page: "noteEternalSunshine",
  category: "AI & CINEMA",
  date: "2026-09-20T20:00:00+09:00",
  sample: false,
  image: "/a/generated/notes/eternal-sunshine-memory.webp",
  imageAlt: {
    ko: "겨울 바닷가의 연인 사진에서 한 사람의 모습만 오려내고, 주변 추억의 사진들과 실로 연결한 콜라주",
    en: "A winter beach photograph with one lover cut out, connected by threads to photographs of everyday memories",
  },
  ko: {
    title: "《이터널 선샤인》을 보다가 엉뚱한 기술력이 부러워졌다",
    summary:
      "전 애인만 잊고 나머지는 멀쩡하다니. AI 모델을 만지다 보니 기억 삭제 회사의 기술력이 새삼 대단해 보였다.",
    sections: [
      {
        title: "",
        paragraphs: [
          "※ 영화 《이터널 선샤인》의 스포일러가 있습니다.",
          "《이터널 선샤인》에는 헤어진 연인의 기억을 지워주는 회사가 나온다. 클레멘타인이 먼저 조엘을 지우고, 그 사실을 알게 된 조엘도 그녀에 대한 기억을 지우러 간다.",
          "처음에는 그 설정이 슬펐다. 얼마나 괴로우면 함께 보낸 시간까지 없애고 싶을까.",
          "그런데 AI 모델을 만지다 보니 다른 부분이 눈에 들어온다.",
          "그 사람만 지웠는데 다른 건 멀쩡하네?",
          "전 애인은 잊었는데 말도 잘하고, 기차도 타고, 일상생활도 한다. 집 주소를 잊거나, 하던 일을 못 하게 되는 것 같지는 않다.",
          "기억을 지우는 것도 대단하지만, 다른 기억을 건드리지 않는 게 더 대단해 보였다.",
          "저 회사 기술팀과 한번 얘기해 보고 싶다.",
          "AI를 만지다 보면 비슷한 바람을 품게 된다. 모델이 너무 커서 양자화를 하고, 불필요한 거절이 많아서 거절하는 성향을 손본다. 작업이 끝나면 원래 잘하던 것들을 다시 시켜 본다.",
          "대답은 하는데 전보다 어색하다. 잘 풀던 문제를 틀린다. 이걸 고치면서 저것도 건드렸나 싶어 설정을 다시 확인한다.",
          "물론 양자화는 숫자의 정밀도를 낮추는 작업이고, 거절 행동을 바꾸는 것은 또 다른 작업이다. 둘 다 특정 기억을 찾아 도려내는 기술은 아니다. 영화처럼 특정 지식을 잊게 하는 연구에는 ‘언러닝’이라는 이름이 따로 있다.",
          "방법은 달라도 바라는 것은 비슷하다.",
          "용량만 줄었으면. 거절만 줄었으면. 그 정보만 잊었으면.",
          "말할 때는 간단한데, 막상 해보면 ‘그것만’이 어렵다.",
          "그래서 전 애인에 관한 기억만 지워준다는 라쿠나사의 서비스가 새삼 대단하게 느껴진다. 나는 모델 하나 손보고도 원래 되던 게 여전히 되는지 확인하느라 한참인데, 여기는 사람을 상대로 그걸 한다.",
          "기억이 폴더에 들어 있다면 간단할 것이다. ‘클레멘타인’ 폴더를 찾아 지우면 된다. 미련이 남을 것 같으면 휴지통도 비운다.",
          "그런데 사람 하나를 떠올려 보면 그렇게 깔끔할 리가 없다.",
          "같이 갔던 바다, 거기서 먹었던 조개구이, 돌아오는 차에서 들었던 노래. 그 사람이 좋아해서 보기 시작했는데 이제는 내가 더 좋아하는 영화. 싸우다가 들었던 말. 기분 나빴지만 나중에 생각해 보니 맞는 말이어서 고친 버릇.",
          "이 가운데 어디까지 지워야 그 사람을 잊었다고 할 수 있을까.",
          "같이 갔던 식당은 기억하면서 맞은편에 누가 앉아 있었는지만 잊을 수도 있나. 식당까지 잊으면 맛있었다는 것도 사라지나.",
          "실연도 억울한데 겨우 찾은 맛집까지 잃기는 싫다.",
          "실제로 이런 서비스가 나왔다면 동의서부터 읽어봐야 할 것 같다.",
          "“시술 후 대상 인물과 관련된 기억이 소실됩니다. 일부 음악 취향과 맛집 정보가 함께 사라질 수 있습니다. 드물게 대상 인물과 아무 관계도 없는 넷플릭스 비밀번호를 잊어버릴 수 있습니다.”",
          "“넷플릭스는 왜요?”",
          "“개인차가 있습니다.”",
          "후기도 꼼꼼히 봐야 한다.",
          "“그 사람은 확실히 잊었어요. 근데 공동현관 비밀번호도 잊어서 집 앞에서 전화했네요.”",
          "이 정도는 어떻게든 수습할 수 있다. 그런데 이런 후기가 있으면 예약을 다시 생각해 봐야 한다.",
          "“시술받고 엑셀 함수가 잘 기억 안 납니다. 업무에는 지장 없다고 하셨는데 확인 부탁드립니다.”",
          "AI에서도 고친 부분이 잘되는 것과 원래 되던 부분이 계속 잘되는 것은 따로 확인해야 한다. 거절이 줄었다고 해서 답변까지 좋아진 것은 아니다. 용량을 줄였어도 내가 쓰던 일을 제대로 못 하면 곤란하다.",
          "기억 삭제도 마찬가지일 것이다.",
          "클레멘타인 사진을 보여줬을 때 ‘모르는 사람인데요’라는 대답을 들었다고 검사가 끝나면 안 된다. 집은 찾아갈 수 있는지, 업무에 필요한 것은 기억하는지, 다른 사람과의 추억은 남아 있는지도 봐야 한다.",
          "나는 아마 시술 전에 업무 관련 시험부터 만들어 놓을 것 같다. 끝나고 점수가 떨어지면 따져야 하니까.",
          "그런데 정작 시술을 받고 나면 틀린 문제를 보고도 원래 몰랐던 것 같다고 생각할 수 있다.",
          "기억을 잃은 사람이 기억 삭제의 품질을 확인해야 한다니, 이건 생각보다 까다로운 서비스다.",
          "영화는 물론 그런 쪽으로 흘러가지 않는다. 조엘은 기억이 지워지는 동안 마음이 바뀐다. 없애고 싶었던 기억 속에, 없애고 싶지 않은 순간도 있다는 걸 뒤늦게 안다.",
          "헤어진 뒤에는 마지막에 겪은 일이 너무 선명해서 그 앞의 시간까지 전부 잘못된 것처럼 느껴질 때가 있다. 막상 하나씩 사라지기 시작하면, 그때 좋았던 것까지 거짓말은 아니었다는 생각이 들 수도 있다.",
          "지우고 싶은 건 같이 웃었던 저녁이 아니었는데.",
          "그 저녁을 떠올릴 때마다 지금 아프다는 게 문제였는데.",
          "신청서에 서명할 때는 그 차이를 미처 생각하지 못했을 것이다.",
          "더 얄궂은 건 기억을 지운 두 사람이 다시 서로에게 끌린다는 점이다.",
          "함께 보낸 시간은 잊었어도, 서로를 좋아했던 이유는 남아 있었나 보다.",
          "그 사람의 어떤 표정에 마음이 움직이는지, 어떤 농담에 웃는지, 왜 하필 저런 성격을 좋아하는지까지 바꿔야 한다면 시술의 범위가 너무 넓어진다.",
          "그 사람을 잊으러 갔는데 내 취향과 성격까지 고쳐야 하는 셈이다. 거기까지 하고 싶은 건 아니었다.",
          "그래서 라쿠나사의 기술은 부럽지만, 막상 이용하라면 망설일 것 같다. 지우고 싶은 기억의 범위를 내가 정확히 정할 자신이 없다. 그 사람과 무관하다고 생각했던 내 취향에도 그 사람이 조금은 묻어 있을 것 같다.",
          "그래도 상담은 한번 받아볼 수 있겠다.",
          "“그 사람은 잊고 싶은데요.”",
          "“네.”",
          "“그 사람이 알려준 맛집은 남겨주세요.”",
          "“관련 기억이라 같이 지워질 수 있습니다.”",
          "“그럼 잠깐만요.”",
          "일단 식당 주소부터 적어야겠다.",
        ],
      },
    ],
  },
  en: {
    title: "The technology I envy in Eternal Sunshine",
    summary:
      "Forget your ex and keep everything else intact? Working with AI has given me a new appreciation for a fictional memory-erasure company.",
    sections: [
      {
        title: "",
        paragraphs: [
          "Spoilers for Eternal Sunshine of the Spotless Mind.",
          "In Eternal Sunshine of the Spotless Mind, a company erases memories of former lovers. Clementine erases Joel first. When he finds out, he goes in to have his memories of her removed too.",
          "At first, I found the premise sad. How much must it hurt to want to lose all that time together?",
          "But after working with AI models, something else caught my attention.",
          "They removed just that person, and everything else still works?",
          "He forgets his ex, but he can still talk, take a train, and get through the day. He does not seem to forget his address or lose the ability to do his job.",
          "Erasing memories is impressive. Leaving the other memories alone seems even more impressive.",
          "I would like a word with their engineering team.",
          "Working with AI inspires similar wishes. A model is too big, so you quantize it. It refuses too many reasonable requests, so you adjust its refusal behavior. Then you run it through the things it used to do well.",
          "It answers, but the wording seems off. It gets a familiar problem wrong. You check the settings again, wondering what else you changed along the way.",
          "Of course, quantization reduces numerical precision, while changing refusal behavior is a different operation. Neither involves cutting out a particular memory. Research into making a model forget specific knowledge has its own name: unlearning.",
          "The methods differ, but the wish is similar.",
          "Just make it smaller. Just reduce the refusals. Just forget that information.",
          "Easy to say. The hard part is ‘just.’",
          "That is why Lacuna’s promise to erase only the memories of an ex suddenly seems remarkable. I spend ages checking whether a modified model still does what it used to. They do this to people.",
          "If memories lived in folders, it would be simple. Find the Clementine folder and delete it. Empty the trash if you think you might change your mind.",
          "But think about one person, and it cannot possibly be that tidy.",
          "The beach you visited together. The grilled clams you ate there. The song playing on the drive home. A film you watched because they liked it, which you now love even more than they do. Something they said during an argument. It stung, but later you realized they had a point, and changed a habit.",
          "How much of that has to go before you can say you have forgotten them?",
          "Can you remember the restaurant but forget who sat across from you? If the restaurant goes too, do you forget how good the food was?",
          "The breakup was bad enough. I would rather not lose a reliably good restaurant as well.",
          "If this service actually existed, I would start by reading the consent form.",
          "‘Memories associated with the designated person will be erased. Some music preferences and restaurant recommendations may also be lost. In rare cases, you may forget your Netflix password, even if it has no connection to the designated person.’",
          "‘Why Netflix?’",
          "‘Results vary.’",
          "I would read the reviews carefully too.",
          "‘Definitely forgot my ex. Also forgot the entry code to my building. Had to call someone from outside.’",
          "Manageable, I suppose. But a review like this would make me reconsider the appointment.",
          "‘Having trouble remembering Excel formulas since the procedure. You said it would not affect my work. Please look into this.’",
          "With AI, checking that the change worked and checking that existing abilities survived are separate jobs. Fewer refusals do not necessarily mean better answers. A smaller model is little use if it can no longer do the work you need.",
          "Memory erasure would be much the same.",
          "You cannot show someone a photograph of Clementine, hear ‘Never seen her before,’ and call the examination complete. Can they find their way home? Do they remember what they need for work? Are their memories of other people still there?",
          "I would probably prepare a work-related test before the procedure. If my score dropped afterward, I would want to bring it up.",
          "Except afterward, I might look at a question I got wrong and assume I never knew the answer in the first place.",
          "Asking someone who has lost their memories to assess the quality of a memory-erasure service is trickier than it sounds.",
          "The film, of course, goes somewhere else. Joel changes his mind while his memories are being erased. Among the memories he wanted gone, he discovers moments he wants to keep.",
          "After a breakup, the ending can be so vivid that everything before it feels like a mistake. But watching those moments disappear, one by one, might remind you that the good parts were real too.",
          "It was not the evening you spent laughing together that you wanted to lose.",
          "The problem was how much it hurt to remember it now.",
          "That distinction might not occur to you while signing the form.",
          "What makes it more bittersweet is that the two people are drawn to each other again after their memories are erased.",
          "Perhaps they forgot their time together, but kept the reasons they liked each other.",
          "If the procedure must also change which expressions move you, which jokes make you laugh, and why you like that particular kind of person, its scope becomes much too large.",
          "You went in to forget someone. Now you have to change your own tastes and personality. That was more than you had in mind.",
          "So I envy Lacuna’s technology, but I would hesitate to use it. I am not sure I could draw an accurate boundary around the memories I want erased. Even tastes I consider entirely my own may carry a little of that person.",
          "Still, I could at least go for a consultation.",
          "‘I would like to forget this person.’",
          "‘Of course.’",
          "‘But please keep the restaurants they recommended.’",
          "‘Those are related memories. They may be erased too.’",
          "‘Give me a minute, then.’",
          "First, I need to write down the addresses.",
        ],
      },
    ],
  },
};
