export const homeCopy = {
  ko: {
    capabilityEyebrow: "AI NATIVE CONSULTING",
    capabilityTitle:
      "일하는 방식부터 제품과 운영까지,\n하나의 흐름으로 연결합니다.",
    capabilityBody:
      "AI Native 전환은 역할과 책임을 정하고, 실제 업무에서 AI를 검증하며, 안정적으로 운영할 기반을 갖추는 일입니다. 조직의 현재 단계에 맞춰 필요한 변화를 함께 만듭니다.",
    capabilities: [
      {
        number: "01",
        eyebrow: "ORGANIZATION & WORKFLOWS",
        title: "함께 일하는 방식",
        body: "사람과 AI의 역할, 의사결정과 검토 책임을 정합니다. 개인의 활용 경험을 팀이 함께 쓰는 업무 흐름과 플레이북으로 만듭니다.",
        strengths: ["역할과 책임", "업무 플레이북", "교육과 확산"],
        image: "/a/generated/consulting/ai-native-honeybees-v3.webp",
        alt: "유기적으로 협업하는 AI Native 조직 이미지",
      },
      {
        number: "02",
        eyebrow: "AI & PRODUCT DELIVERY",
        title: "실제 업무에서 검증",
        body: "현장 질문과 문서, 예외 사례를 기준으로 AI·RAG·에이전트를 평가합니다. 검색과 도구 호출, 사람의 검토를 신뢰할 수 있는 서비스 흐름으로 연결합니다.",
        strengths: ["AI·RAG 평가", "에이전트와 도구", "품질·비용·속도"],
        image: "/a/generated/consulting/ax-human-orchestration-v5.webp",
        alt: "사람과 AI가 하나의 흐름으로 협업하는 AX 이미지",
      },
      {
        number: "03",
        eyebrow: "PLATFORM & OPERATIONS",
        title: "지속해서 운영할 기반",
        body: "공통 개발 환경과 배포 자동화, 모니터링을 연결합니다. 팀이 반복해서 제품을 개선할 수 있도록 품질·장애·비용 관리 기준을 세웁니다.",
        strengths: ["개발·배포 자동화", "관찰 가능성", "운영 거버넌스"],
        image: "/a/generated/consulting/platform-beaver-dam-v4.webp",
        alt: "안정적인 흐름을 만드는 플랫폼 엔지니어링 이미지",
      },
    ],
    worksEyebrow: "BUILT & OPERATED",
    worksTitle: "직접 만들고 운영하며\n실행의 기준을 쌓습니다.",
    worksBody:
      "AI 콘텐츠 자동화부터 서비스 주문과 배포까지, 직접 기획하고 개발한 제품입니다. 아이디어를 검증하고 실제 운영으로 연결하는 접근 방식을 담았습니다.",
    works: [
      {
        eyebrow: "AI CONTENT PIPELINE",
        title: "AI Slop",
        body: "AI가 이야기와 장면을 기획하고, 이미지 생성과 게시까지 이어 가는 자동 연재 실험입니다. 만화와 영상을 꾸준히 만드는 하나의 콘텐츠 파이프라인으로 운영합니다.",
        image: "/a/versions/works/20260720/wind-returning-place.jpg",
        alt: "AI Slop 대표 연재 바람이 돌아오는 곳",
        internalAction: "프로젝트 소개",
        internalHref: "/works/ai-slop",
        externalAction: "Slop 바로가기",
        externalHref: "https://slop.jjgo.io/",
      },
      {
        eyebrow: "PRODUCT SHOWROOM SAAS",
        title: "OKGo",
        body: "사이트, 게임, 만화, 쇼츠, 키오스크와 알림 서비스를 한곳에서 고르고 주문할 수 있는 쇼룸형 SaaS입니다. 아이디어가 실제 배포와 운영으로 이어지는 과정을 제품으로 담았습니다.",
        image: "/a/versions/works/20260720/okgo4.jpg",
        alt: "OKGo 서비스 쇼룸 화면",
        internalAction: null,
        internalHref: null,
        externalAction: "OKGo 바로가기",
        externalHref: "https://okgo4.jjgo.io/",
      },
    ],
    robloxEyebrow: "BUILDING IN ROBLOX",
    robloxTitle: "플레이를 만들고,\n다음 제작을 더 빠르게 만듭니다.",
    robloxBody:
      "서울 수로를 여행하는 종이배 탐험과 폭탄 비에서 살아남는 경쟁 게임을 만들었습니다. 작은 플레이를 빠르게 검증하고, Lua 스크립트와 제작 도구를 재사용 가능한 기반으로 쌓습니다.",
    robloxTags: ["게임 기획", "Lua 스크립팅", "제작 도구", "출시와 운영"],
    robloxAction: "Roblox 게임 만들기 보기",
    robloxImageAltOne: "Roblox 종이배 서울 수로 탐험 게임 화면",
    robloxImageAltTwo: "Roblox Bomb Rain 게임 화면",
    allWorks: "모든 작품 둘러보기",
    heroIntro: "이정주 · AI NATIVE CONSULTING",
    heroTitle: "AI와 함께 일하는 조직,\n실제로 작동하는 제품을 만듭니다.",
    heroAction: "AI Native 접근 방식 보기",
    consultingOutcome:
      "함께 만드는 것: AI 운영 모델 · 검증된 업무 흐름과 평가셋 · 반복 가능한 개발·운영 기반",
    consultingAction: "AI Native 컨설팅 자세히 보기",
  },
  en: {
    capabilityEyebrow: "AI NATIVE CONSULTING",
    capabilityTitle: "Connect how teams work\nto products and operations.",
    capabilityBody:
      "Becoming AI Native means defining ownership, validating AI against real work, and building the foundation to operate reliably. We shape the changes that fit your organization’s current stage.",
    capabilities: [
      {
        number: "01",
        eyebrow: "ORGANIZATION & WORKFLOWS",
        title: "Work together with AI",
        body: "Define human and AI roles, decision rights, and review responsibilities. Turn individual know-how into shared workflows and playbooks.",
        strengths: [
          "Roles & ownership",
          "Workflow playbooks",
          "Training & adoption",
        ],
        image: "/a/generated/consulting/ai-native-honeybees-v3.webp",
        alt: "An organically coordinated AI-native organization",
      },
      {
        number: "02",
        eyebrow: "AI & PRODUCT DELIVERY",
        title: "Validate against real work",
        body: "Evaluate AI, RAG, and agents using real questions, documents, and edge cases. Connect retrieval, tools, and human review into a dependable service.",
        strengths: [
          "AI & RAG evaluation",
          "Agents & tools",
          "Quality, cost & latency",
        ],
        image: "/a/generated/consulting/ax-human-orchestration-v5.webp",
        alt: "A person and AI working together in one orchestrated flow",
      },
      {
        number: "03",
        eyebrow: "PLATFORM & OPERATIONS",
        title: "Build for ongoing operation",
        body: "Connect shared development environments, deployment automation, and monitoring. Define how teams manage quality, incidents, and cost as they improve the product.",
        strengths: [
          "Delivery automation",
          "Observability",
          "Operational governance",
        ],
        image: "/a/generated/consulting/platform-beaver-dam-v4.webp",
        alt: "Platform engineering creating a stable, dependable flow",
      },
    ],
    worksEyebrow: "BUILT & OPERATED",
    worksTitle: "Built in practice.\nImproved through operation.",
    worksBody:
      "From AI content automation to service ordering and delivery, these are products I have designed and built. They show how I move from an idea to validation and ongoing operation.",
    works: [
      {
        eyebrow: "AI CONTENT PIPELINE",
        title: "AI Slop",
        body: "An automated publishing experiment in which AI plans stories and scenes, creates imagery, and carries the work through publication as an ongoing comics and video pipeline.",
        image: "/a/versions/works/20260720/wind-returning-place.jpg",
        alt: "The Place Where the Wind Returns, a featured AI Slop series",
        internalAction: "Project story",
        internalHref: "/works/ai-slop",
        externalAction: "Visit Slop",
        externalHref: "https://slop.jjgo.io/",
      },
      {
        eyebrow: "PRODUCT SHOWROOM SAAS",
        title: "OKGo",
        body: "A showroom SaaS for browsing and ordering sites, games, comics, shorts, kiosks, and notification services—turning an idea into a path through delivery and operation.",
        image: "/a/versions/works/20260720/okgo4.jpg",
        alt: "The OKGo service showroom",
        internalAction: null,
        internalHref: null,
        externalAction: "Visit OKGo",
        externalHref: "https://okgo4.jjgo.io/",
      },
    ],
    robloxEyebrow: "BUILDING IN ROBLOX",
    robloxTitle: "Build the play, then make\nthe next build faster.",
    robloxBody:
      "I created a relaxing paper-boat journey through Seoul and a competitive survival game beneath a rain of bombs. Each focused playtest becomes reusable Lua systems and better creation tools.",
    robloxTags: [
      "Game design",
      "Lua scripting",
      "Creation tools",
      "Launch & operations",
    ],
    robloxAction: "Explore Roblox game making",
    robloxImageAltOne:
      "Paper Boat Exploration through Seoul waterways on Roblox",
    robloxImageAltTwo: "Bomb Rain survival game on Roblox",
    allWorks: "Explore all works",
    heroIntro: "JUNGJU LEE · AI NATIVE CONSULTING",
    heroTitle: "Build teams that work with AI.\nDeliver products that work.",
    heroAction: "Explore the AI Native approach",
    consultingOutcome:
      "What we build: an AI operating model, validated workflows and evaluation sets, and repeatable delivery and operations.",
    consultingAction: "Explore AI Native consulting",
  },
} as const;
