import type { ConsultingService } from "./consulting-components";

export const consultingServicesEn: ConsultingService[] = [
  {
    slug: "ai-native",
    number: "01",
    english: "AI-NATIVE ORGANIZATION",
    title: "Building an AI-Native Organization",
    shortTitle: "AI-Native Organization",
    summary: "Make AI part of how the whole organization decides, collaborates, and builds products—not a tool used by a few individuals.",
    detailTitle: "An organization built to solve problems",
    detailSummary: "Build an organization that solves meaningful problems with AI.",
    image: "/a/generated/consulting/ai-native-honeybees-v3.webp",
    keywords: ["Operating model", "Ways of working", "AI enablement"],
    proofTitle: "Turn product engineering experience into an operating system for the organization.",
    proofBody: "This goes beyond tool training. Strategy, technology, and culture are connected so AI becomes part of product development, decision-making, code review, testing, and knowledge sharing.",
    metrics: [
      { value: "16 yrs", label: "Product engineering", detail: "From Daum, Kakao, and NCSOFT to AI product organizations" },
      { value: "6 stages", label: "Experience expanded", detail: "Web, API, cloud, DevOps, MLOps, and AI-native work" },
      { value: "4 pillars", label: "Transformation design", detail: "Strategy, workflow, technology, and culture" },
      { value: "1 team", label: "Pilot starting point", detail: "Validate small, then scale across the organization" },
    ],
    expertise: [
      { title: "AI Operating Model", body: "Define how people and AI divide work, make decisions, review outcomes, and remain accountable through reusable operating principles." },
      { title: "AI Workflow Design", body: "Identify high-value work across planning, development, review, testing, and documentation, then connect prompts, agents, and tools into the flow." },
      { title: "Governance & Quality", body: "Balance speed with safety through security boundaries, result validation, traceability, and human-in-the-loop controls." },
      { title: "Adoption & Capability", body: "Design capability standards, coaching, communities of practice, and measures that turn adoption into organizational learning." },
    ],
    situations: [
      "AI capability varies widely and effective practices remain individual know-how.",
      "Tools are available, but unclear accountability and quality standards prevent measurable outcomes.",
      "Roles, collaboration, and product development need to be redesigned for the AI era.",
    ],
    outcomes: [
      { title: "AI operating model", body: "A practical model covering principles, responsibilities, approvals, and review controls aligned to organizational goals and risk." },
      { title: "Core workflow playbooks", body: "Reusable prompts, agent flows, quality checklists, and measures for the work where AI creates the most value." },
      { title: "Scale-up roadmap", body: "A 90-day execution plan that turns pilot learning into standards, training, communities, and leadership routines." },
    ],
    process: [
      { period: "1–2 weeks", title: "Assess", body: "Use interviews and workflow observation to map AI maturity, repetitive work, and quality or security constraints." },
      { period: "2 weeks", title: "Design", body: "Define the target operating model, priority workflows, accountability, and success measures." },
      { period: "4–6 weeks", title: "Pilot", body: "Validate the new workflow and tool system inside one team’s real product delivery process." },
      { period: "90 days", title: "Scale", body: "Extend proven practices through standards, learning programs, communities, and leadership cadence." },
    ],
  },
  {
    slug: "ax",
    number: "02",
    english: "AI TRANSFORMATION",
    title: "AX",
    shortTitle: "AX",
    summary: "Reframe the business and customer experience through AI, then turn the strongest opportunities into services and operational change.",
    detailTitle: "Transforming business with AI",
    detailSummary: "Find valuable opportunities and turn them into real services and better ways of working.",
    image: "/a/generated/consulting/ax-dragonfly-v3.webp",
    keywords: ["Opportunity discovery", "Service design", "PoC & roadmap"],
    proofTitle: "Connect ideas to products that operate in the real world.",
    proofBody: "The work considers customer problems, business value, data, and operational constraints—not technical possibility alone. Hands-on experience from discovery through PoC, productization, and operations leads to executable decisions.",
    metrics: [
      { value: "8+", label: "Industry domains", detail: "Healthcare, finance, games, portals, infrastructure, security, and more" },
      { value: "20+", label: "Products & platforms", detail: "From design through development, deployment, and operations" },
      { value: "3 lenses", label: "Opportunity evaluation", detail: "Customer value, business impact, and technical feasibility" },
      { value: "1 PoC", label: "Starting point", detail: "Test the core hypothesis with working evidence" },
    ],
    expertise: [
      { title: "Opportunity Portfolio", body: "Discover AI opportunities across customer journeys and workflows, then prioritize investment by value, feasibility, and risk." },
      { title: "Service & Workflow", body: "Make human–AI collaboration, exception handling, operations, and accountability tangible through a service blueprint." },
      { title: "Data & AI Fit", body: "Assess data, model and agent architecture, quality criteria, and security or regulatory limits to test realism early." },
      { title: "PoC to Product", body: "Move beyond demos by defining KPIs, economics, operating requirements, a product backlog, and staged investment evidence." },
    ],
    situations: [
      "There are many AI ideas, but no clear way to prioritize them by customer and business value.",
      "PoCs keep being built without becoming products, operational workflows, or measurable business outcomes.",
      "A focused experiment is needed to account for data, security, and regulatory constraints before scaling investment.",
    ],
    outcomes: [
      { title: "AI opportunity portfolio", body: "A near- and mid-term investment map scored by customer value, business impact, data readiness, risk, and cost." },
      { title: "Service blueprint & PoC", body: "A designed customer journey and human–AI operating flow, validated through a working prototype." },
      { title: "Business case", body: "A shared roadmap combining KPIs, expected impact, economics, operating requirements, and the productization backlog." },
    ],
    process: [
      { period: "1–2 weeks", title: "Discover", body: "Structure customer and frontline insights, journeys, workflows, data, and constraints." },
      { period: "1 week", title: "Select", body: "Choose the opportunity with the strongest evidence using a value, feasibility, and risk matrix." },
      { period: "4–6 weeks", title: "Validate", body: "Measure user value, quality, and operating-cost assumptions with a service prototype and PoC." },
      { period: "2 weeks", title: "Mobilize", body: "Create an execution roadmap covering KPIs, governance, product backlog, and investment sequence." },
    ],
  },
  {
    slug: "platform-engineering",
    number: "03",
    english: "PLATFORM ENGINEERING",
    title: "Platform Engineering",
    shortTitle: "Platform Engineering",
    summary: "Build a shared platform and operating foundation so developers can focus on product value instead of infrastructure complexity.",
    detailTitle: "A platform that accelerates delivery",
    detailSummary: "Reduce complexity and create the foundation teams need to focus on products.",
    image: "/a/generated/consulting/platform-beaver-dam-v4.webp",
    keywords: ["Developer platform", "CI/CD", "Operations automation"],
    proofTitle: "Build the platform as an internal product—not another technology project.",
    proofBody: "Experience designing and operating DBaaS, KaaS, cloud portals, and medical AI platforms brings developer experience and operational reliability into one view. The goal is not more infrastructure; it is lower cognitive load and faster delivery for product teams.",
    metrics: [
      { value: "10K+", label: "Servers at scale", detail: "Managed through automation and operations platforms" },
      { value: "20+", label: "Products & platforms", detail: "Across design, development, deployment, and operations" },
      { value: "6 areas", label: "Engineering connected", detail: "Backend, frontend, cloud, DevOps/SRE, MLOps, and data" },
      { value: "3 layers", label: "Platform design", detail: "Developer experience, delivery automation, and reliability" },
    ],
    expertise: [
      { title: "Platform as a Product", body: "Treat developers as customers and shape the platform vision and backlog around journeys, pain points, and adoption measures." },
      { title: "Reference Architecture", body: "Design boundaries and integration across portals, service catalogs, IDPs, and observability within technical, security, and cost constraints." },
      { title: "Golden Path & Automation", body: "Implement safe defaults and self-service automation from project creation through build, test, deployment, and observability." },
      { title: "SRE & Governance", body: "Operate speed and reliability together through SLOs, error budgets, policy automation, cost visibility, and a clear support model." },
    ],
    situations: [
      "Every team builds, deploys, and observes differently, increasing duplicated work and operational load.",
      "Cloud, security, and infrastructure complexity are increasing cognitive load and slowing product delivery.",
      "The organization needs stronger standards, cost efficiency, and reliability without taking autonomy away from developers.",
    ],
    outcomes: [
      { title: "Platform product strategy", body: "A clear definition of platform customers, value proposition, boundaries, priorities, and success measures tied to developer journeys and organizational goals." },
      { title: "Reference architecture & golden path", body: "A working self-service path connecting portal, catalog, CI/CD, IaC, and observability for real product teams." },
      { title: "Operating & governance model", body: "A sustainable structure for platform responsibilities, team autonomy, SLOs, policy automation, support, and cost." },
    ],
    process: [
      { period: "2–3 weeks", title: "Assess", body: "Measure wait time, repetitive work, and reliability or security bottlenecks through developer interviews and delivery-flow analysis." },
      { period: "1–2 weeks", title: "Prioritize", body: "Select the first platform product area using developer value, operational impact, and implementation cost." },
      { period: "6–12 weeks", title: "Build", body: "Create a golden path with a real product team, including portal, templates, pipelines, and observability." },
      { period: "Ongoing", title: "Productize", body: "Run the platform backlog using adoption, lead time, deployment, recovery, and feedback measures." },
    ],
  },
];
