// Auto-generated by scripts/sync-content-to-src.mjs
// Do not edit this file directly.

export const generatedStories = [
	{
		"slug": "repo-todo-service",
		"title": "todo-service 레포 스냅샷",
		"summary": "JavaScript 기반 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2026-02-16",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/todo-service",
					"- Visibility: public",
					"- Primary Language: JavaScript",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2026-02-16 03:46:27 UTC",
					"- Last Push: 2026-02-16 03:46:29 UTC",
					"- Last Update: 2026-02-16 03:46:32 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-test",
		"title": "test 레포 스냅샷",
		"summary": "기술 스택 미정 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2026-02-14",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/test",
					"- Visibility: private",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2026-02-14 00:22:35 UTC",
					"- Last Push: 2026-02-14 00:23:51 UTC",
					"- Last Update: 2026-02-14 00:22:47 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-jgo",
		"title": "jgo 레포 스냅샷",
		"summary": "Go 기반 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2026-02-13",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/jgo",
					"- Visibility: public",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2026-02-13 03:04:07 UTC",
					"- Last Push: 2026-02-16 11:50:13 UTC",
					"- Last Update: 2026-02-16 11:50:17 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "dad-daughter-english-study",
		"title": "아빠와 딸을 위한 영어 공부 사이트",
		"summary": "study.jjgo.io에서 빈칸/퀴즈/대화/한영 음성으로 꾸준히 학습하는 가족 영어 공부 사이트",
		"date": "2026-02-12",
		"tags": [
			"personal-site",
			"english-study",
			"elevenlabs",
			"gpt"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posts/2026-02-12-dad-daughter-english-study/study-home.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posts/2026-02-12-dad-daughter-english-study/study-home.svg",
		"content": [
			{
				"heading": "아빠와 딸을 위한 영어 공부 사이트",
				"body": [
					"`https://study.jjgo.io`는 아빠와 딸이 함께 꾸준히 공부하려고 만든 영어 학습 사이트다.",
					"핵심은 복잡한 커리큘럼보다, 매일 반복하기 쉬운 학습 흐름을 만드는 것이다.",
					"---"
				]
			},
			{
				"heading": "여기서 할 수 있는 것",
				"body": [
					"- 빈칸 맞추기",
					"- 퀴즈 풀이",
					"- 대화 학습",
					"- 영어/한국어 음성 청취",
					"운전 중에도 학습이 가능하고, 필요할 때는 빠르게 문제만 반복해서 볼 수 있게 구성했다.",
					"---"
				]
			},
			{
				"heading": "음성 제작 방식",
				"body": [
					"음성은 ElevenLabs를 사용해서 만들었다.",
					"- 음성용 프롬프트는 GPT로 생성",
					"- 생성된 스크립트를 ElevenLabs로 반자동 음성화",
					"- 학습 흐름에 맞춰 음성을 계속 추가/개선",
					"콘텐츠를 빠르게 늘리면서도, 실제로 들었을 때 자연스럽게 공부되도록 관리하고 있다.",
					"---"
				]
			},
			{
				"heading": "실제 학습 루틴",
				"body": [
					"- 매일 꾸준히 공부 중",
					"- 운전하면서도 학습 가능",
					"- 수면모드가 있어서 30분 후 자동 종료",
					"짧게 자주 반복할 수 있어서 장기적으로 학습 루틴을 유지하기 좋다.",
					"---"
				]
			},
			{
				"heading": "화면 예시",
				"body": [
					"![첫 페이지](/posts/2026-02-12-dad-daughter-english-study/study-home.svg)",
					"![가상 회의 대화 학습 페이지](/posts/2026-02-12-dad-daughter-english-study/study-dialogue.svg)",
					"![퀴즈 페이지](/posts/2026-02-12-dad-daughter-english-study/study-quiz.svg)",
					"---"
				]
			},
			{
				"heading": "장점",
				"body": [
					"이 사이트의 큰 장점은 **내 도메인에 최적화된 영어를 공부할 수 있다는 점**이다.",
					"실제로 자주 쓰는 문맥과 상황에 맞춰 학습할 수 있어서, 일반 예문보다 훨씬 실용적으로 쌓인다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-jjgo",
		"title": "jjgo 레포 스냅샷",
		"summary": "JavaScript 기반 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2026-02-12",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/jjgo",
					"- Visibility: public",
					"- Primary Language: JavaScript",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2026-02-12 05:32:51 UTC",
					"- Last Push: 2026-02-13 01:17:00 UTC",
					"- Last Update: 2026-02-13 01:17:03 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "rag-latency-retro",
		"title": "RAG 지연 줄이기 회고",
		"summary": "검색과 직렬화 병목을 분리해서 응답 지연을 줄인 과정 정리.",
		"date": "2026-02-11",
		"tags": [
			"rag",
			"performance",
			"retrospective"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "본문",
				"body": [
					"검색 품질은 괜찮았지만 응답 시작이 느렸다. 이번 글은 병목을 잘라서 본 과정 기록이다."
				]
			},
			{
				"heading": "문제",
				"body": [
					"- 사용자는 정답률보다 첫 응답 속도에 더 민감했다.",
					"- 같은 질문이 반복되는데도 캐시 적중률이 낮았다."
				]
			},
			{
				"heading": "조치",
				"body": [
					"1. 전처리 직렬화 단계를 경량 포맷으로 교체",
					"2. 상위 반복 질의를 메모리 캐시에 고정",
					"3. 응답 스트리밍 시작 시점을 앞당김"
				]
			},
			{
				"heading": "결과",
				"body": [
					"- 체감 응답 속도 개선",
					"- 재시도율 감소",
					"- 회귀 확인용 지표를 대시보드에 추가"
				]
			},
			{
				"heading": "다음",
				"body": [
					"- 질문 유형별 캐시 전략 분리",
					"- 주간 회귀 리포트 자동화"
				]
			}
		],
		"links": []
	},
	{
		"slug": "ui-a11y-fix-log",
		"title": "UI 접근성 수정 로그",
		"summary": "키보드 접근성과 클릭 가능한 정적 요소 문제를 정리하고 수정한 기록.",
		"date": "2026-02-10",
		"tags": [
			"frontend",
			"a11y",
			"svelte"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "본문",
				"body": [
					"체크 도구 경고를 쌓아두면 나중에 고치기 더 어렵다. 작게 나눠서 바로바로 수정했다."
				]
			},
			{
				"heading": "발견",
				"body": [
					"- 클릭 이벤트가 있는 비상호작용 요소 존재",
					"- 이미지 alt 누락",
					"- 자기닫힘 태그 사용으로 마크업 경고 발생"
				]
			},
			{
				"heading": "수정",
				"body": [
					"1. `div` 클릭 UI를 버튼/링크로 교체",
					"2. 이미지에 의미 있는 alt 추가",
					"3. `audio` 태그를 명시적 닫힘 태그로 변경"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 기능보다 사용성 기본기부터 유지",
					"- 경고 1개라도 PR 전에 정리"
				]
			}
		],
		"links": []
	},
	{
		"slug": "prod-incident-001",
		"title": "장애 기록 #001 - 정적 파일 경로 이슈",
		"summary": "배포 후 일부 페이지의 정적 리소스 경로가 깨진 장애와 복구 과정.",
		"date": "2026-02-09",
		"tags": [
			"incident",
			"ops",
			"postmortem"
		],
		"category": "operations",
		"categoryName": "Operations",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "본문",
				"body": [
					"배포 직후 일부 브라우저에서 포스터 이미지가 로드되지 않았다. 원인은 단순했지만 발견까지 시간이 걸렸다."
				]
			},
			{
				"heading": "영향",
				"body": [
					"- 카드 썸네일 일부 미노출",
					"- 상세 페이지 배경 포스터 폴백 실패"
				]
			},
			{
				"heading": "원인",
				"body": [
					"1. 상대 경로와 base 경로 혼용",
					"2. 환경별 경로 접두어 누락"
				]
			},
			{
				"heading": "조치",
				"body": [
					"- 모든 정적 자산 경로 규칙 통일",
					"- 배포 후 체크리스트에 리소스 로드 점검 추가"
				]
			},
			{
				"heading": "회고",
				"body": [
					"- \"작은 경로 차이\"가 장애로 이어진다.",
					"- 복구보다 사전 검증 자동화가 비용이 낮다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "ci-cd-small-wins",
		"title": "CI/CD 소소한 개선 모음",
		"summary": "작지만 반복되는 배포 불편을 줄인 자동화 개선 목록.",
		"date": "2026-02-08",
		"tags": [
			"ci-cd",
			"automation",
			"devops"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "본문",
				"body": [
					"큰 리팩토링보다 작은 자동화가 팀 시간을 더 많이 절약할 때가 많다. 이번 주는 그 작은 개선에 집중했다."
				]
			},
			{
				"heading": "적용한 것",
				"body": [
					"- 빌드 전 콘텐츠 동기화(`make content`)를 파이프라인에 강제",
					"- 실패 로그에서 핵심 에러 라인만 먼저 노출",
					"- 배포 전 체크 타임아웃과 재시도 정책 조정"
				]
			},
			{
				"heading": "효과",
				"body": [
					"1. 배포 전 누락 이슈 감소",
					"2. 실패 원인 확인 시간 단축",
					"3. 수동 확인 단계 축소"
				]
			},
			{
				"heading": "다음 주 계획",
				"body": [
					"- 체크 결과를 슬랙 요약 메시지로 발송",
					"- 릴리즈 노트 자동 생성 실험"
				]
			}
		],
		"links": []
	},
	{
		"slug": "prompt-eval-weekly",
		"title": "Prompt Eval 주간 노트1",
		"summary": "프롬프트 변경이 품질 지표에 미친 영향을 주간 단위로 기록.",
		"date": "2026-02-07",
		"tags": [
			"prompt",
			"eval",
			"quality"
		],
		"category": "research",
		"categoryName": "Research",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "본문",
				"body": [
					"프롬프트는 작은 문장 차이로 결과가 크게 달라진다. 이번 주는 변경 이력과 평가를 같이 봤다."
				]
			},
			{
				"heading": "이번 주 변경",
				"body": [
					"1. 역할 지시 문장을 짧게 정리",
					"2. 출력 포맷 제약을 명확화",
					"3. 금지 표현 목록을 시스템 프롬프트로 이동"
				]
			},
			{
				"heading": "관찰",
				"body": [
					"- 길이 제약을 명확히 할수록 응답 일관성이 올라갔다.",
					"- 과한 제약은 설명력 저하로 이어졌다."
				]
			},
			{
				"heading": "결론",
				"body": [
					"- \"짧고 명확한 지시 + 최소 제약\"이 현재 데이터셋에서 가장 안정적이었다."
				]
			},
			{
				"heading": "액션",
				"body": [
					"- 실패 케이스를 유형별로 태깅",
					"- 다음 주에는 회귀 케이스 비율을 지표로 추가"
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-local-server",
		"title": "local-server 레포 스냅샷",
		"summary": "Dockerfile 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2026-01-26",
		"tags": [
			"devlog",
			"ops",
			"devops"
		],
		"category": "operations",
		"categoryName": "Operations",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/local-server",
					"- Visibility: private",
					"- Primary Language: Dockerfile",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2026-01-26 09:41:40 UTC",
					"- Last Push: 2026-02-18 04:46:42 UTC",
					"- Last Update: 2026-02-18 04:46:45 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-jdex",
		"title": "jdex 레포 스냅샷",
		"summary": "Luau 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2026-01-19",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/jdex",
					"- Visibility: private",
					"- Primary Language: Luau",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2026-01-19 16:27:32 UTC",
					"- Last Push: 2026-01-20 03:20:35 UTC",
					"- Last Update: 2026-01-20 03:20:39 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-roblox-eng",
		"title": "roblox-eng 레포 스냅샷",
		"summary": "기술 스택 미정 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2026-01-02",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/roblox-eng",
					"- Visibility: private",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2026-01-02 15:41:38 UTC",
					"- Last Push: 2026-01-02 15:44:18 UTC",
					"- Last Update: 2026-01-02 15:44:21 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-eng-meeting",
		"title": "eng-meeting 레포 스냅샷",
		"summary": "Svelte 기반 공개 레포. 영어공부",
		"date": "2025-03-03",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/eng-meeting",
					"- Visibility: public",
					"- Primary Language: Svelte",
					"- Homepage: https://study.jjgo.io/",
					"- Description: 영어공부"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2025-03-03 03:46:07 UTC",
					"- Last Push: 2025-12-27 06:31:40 UTC",
					"- Last Update: 2025-12-27 07:53:21 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-allshot",
		"title": "allshot 레포 스냅샷",
		"summary": "JavaScript 기반 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2024-10-10",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/allshot",
					"- Visibility: public",
					"- Primary Language: JavaScript",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2024-10-10 13:03:02 UTC",
					"- Last Push: 2026-02-12 09:51:14 UTC",
					"- Last Update: 2026-02-12 10:23:21 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-allshot-editor",
		"title": "allshot-editor 레포 스냅샷",
		"summary": "JavaScript 기반 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2024-10-02",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/allshot-editor",
					"- Visibility: public",
					"- Primary Language: JavaScript",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2024-10-02 01:53:04 UTC",
					"- Last Push: 2026-02-12 09:59:29 UTC",
					"- Last Update: 2026-02-12 10:22:48 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "shorts",
		"title": "쇼츠생성기",
		"summary": "처음 AI에 의존해서 개발을 한 리엑트기반 쇼츠생성기 저작도구",
		"date": "2024-09-01",
		"tags": [
			"react",
			"personal-site"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "/posts/2026-09-01-shorts/shorts-editor-teaser.mp4",
		"cardPoster": "/posts/2026-09-01-shorts/20240901-shorts-editor-main-screenshot-01.png",
		"bgVideoSrc": "/posts/2026-09-01-shorts/shorts-editor-teaser.mp4",
		"bgPoster": "/posts/2026-09-01-shorts/20240901-shorts-editor-main-screenshot-01.png",
		"content": [
			{
				"heading": "오직 AI만으로 끝까지 밀어붙인 첫 프로젝트",
				"body": [
					"이 프로젝트는 **내가 ‘혼자’ 개발했다기보다, AI와 끝없는 대화를 하면서 완성한 결과물**에 가깝다. 리액트(React) 기반의 쇼츠 생성기 저작도구를 만들면서, 레이아웃부터 컴포넌트 구조, 상태 관리, 기능 구현까지 대부분의 과정을 **챗(대화) 중심으로** 진행했다.",
					"지금 돌이켜보면 이건 “AI가 코드를 대신 써줬다” 같은 단순한 이야기가 아니라, **AI와 함께 개발하는 방식 자체를 몸으로 익힌 기록**이었다.",
					"---"
				]
			},
			{
				"heading": "2024년 9월 1일의 GPT: 가능성은 컸고, 맥락은 얇았다",
				"body": [
					"당시 GPT는 이미 코드 생성과 리팩터링에 꽤 쓸만했지만, 동시에 분명한 특징이 있었다.",
					"- **짧은 요청엔 강하지만, 긴 맥락을 한 번에 완벽하게 잡기 어렵다**",
					"- “전체 프로젝트” 관점보다는 “지금 붙여넣은 코드”에 강하게 반응한다",
					"- 작은 수정 요청이 **의도치 않게 다른 기능을 깨는** 일이 생각보다 자주 생긴다",
					"- 결과적으로, 개발 흐름은 **대화 → 코드 생성 → 복사/붙여넣기 → 에러 → 재대화**의 반복이 된다",
					"그래서 이 프로젝트는 처음부터 끝까지 “AI가 다 해줌”이 아니라, **사람이 방향을 잡고, AI가 힘을 보태고, 다시 사람이 정리하는 협업**으로 진행될 수밖에 없었다.",
					"---"
				]
			},
			{
				"heading": "개발 순서: PPT → HTML → React → 끝없는 챗",
				"body": [
					"이 프로젝트의 시작은 IDE가 아니라 **PPT**였다. 먼저 PPT에서 화면을 구성하며, 내가 만들고 싶은 저작도구의 구조를 “눈으로 보이게” 만들었다.",
					"### 1) PPT로 레이아웃 만들기",
					"- 좌측: 소재/리스트 영역",
					"- 중앙: 프리뷰 영역",
					"- 우측: 편집 패널(텍스트/타이밍/스타일)",
					"- 상단: 저장/내보내기/프리셋 등 액션 영역",
					"이 단계에서 중요한 건 “예쁘게”가 아니라, **사용 흐름이 자연스럽게 이어지는 화면 구조를 잡는 것**이었다.",
					"### 2) GPT 챗으로 HTML 변환 요청 PPT 레이아웃을 바탕으로 GPT에게 화면 구조를 설명하고, 그걸 **HTML 마크업 구조로 변환**해달라고 요청했다.",
					"아래는 그때 레이아웃을 HTML로 옮겨가던 흔적이다.",
					"![레이아웃 HTML 스케치 01](/posts/2026-09-01-shorts/20240901-shorts-editor-layout-html-01.png)",
					"![레이아웃 HTML 스케치 02](/posts/2026-09-01-shorts/20240901-shorts-editor-layout-html-02.png)",
					"### 3) 리액트 코드로 변환 요청 HTML이 어느 정도 잡히면, 그 다음은 React로 옮기는 단계였다.",
					"- 컴포넌트로 분리",
					"- 상태(state) 설계",
					"- 이벤트 핸들링 연결",
					"- 편집 데이터 구조 정의",
					"이때부터는 “화면이 보이는 것”보다 **기능이 일관되게 동작하는 것**이 목표가 됐다.",
					"### 4) 계속 챗으로 개발 이후는 말 그대로 계속 챗이었다.",
					"- GPT에게 코드를 받는다",
					"- 붙여넣는다",
					"- 에러가 난다 (혹은 의도와 다르게 동작한다)",
					"- 에러 로그/증상/의도를 다시 설명한다",
					"- 수정된 코드를 다시 받는다",
					"- 다시 붙여넣는다",
					"이 과정이 “한두 번”이 아니라, 체감상 **끝이 보이지 않을 정도로 반복**됐다. 하지만 그 반복 덕분에, 나는 단순히 기능을 구현한 게 아니라 **AI와 함께 개발이 굴러가게 만드는 감각**을 점점 더 확실히 갖게 됐다.",
					"---"
				]
			},
			{
				"heading": "100줄이 넘어가면 무조건 쪼갰다: AI 협업에서 컴포넌트화는 생존 전략",
				"body": [
					"AI가 코드를 잘 뽑아줄수록 욕심이 생긴다. 한 파일에 기능을 계속 붙이다 보면 금방 100줄, 200줄을 넘는다.",
					"그런데 어느 순간부터 확실히 느꼈다.",
					"- 소스가 길어질수록 GPT의 수정 정확도가 떨어진다",
					"- “부분 수정”을 부탁했는데 “전체 구조”를 흔들어버리는 일이 늘어난다",
					"- 내가 의도한 아키텍처가 대화 중에 흐려진다",
					"그래서 원칙을 만들었다.",
					"> **한 파일이 100줄을 넘으면 쪼갠다.** > UI / 로직 / 유틸을 분리하고, 컴포넌트 단위로 작은 승리를 반복한다.",
					"결과적으로 이 습관이 프로젝트를 살렸다. (그리고 이건 지금 시점에서도 여전히 유효한 방식이다.)",
					"---"
				]
			},
			{
				"heading": "zip 업로드 + README.md + GPT.md: “AI가 프로젝트를 이해하게 만들고 싶었다”",
				"body": [
					"반복 대화에서 가장 힘든 순간은 매번 맥락을 다시 설명하는 일이었다.",
					"- “이 컴포넌트는 왜 존재해?”",
					"- “이 상태는 어디서 오고 어디로 가?”",
					"- “이 기능은 어떤 순서로 동작해야 해?”",
					"AI는 기본적으로 내가 지금 보여준 정보에 강하게 반응하니까, **전체 맥락을 ‘문서’로 고정해두는 장치**가 필요했다.",
					"그래서 시도한 게:",
					"- 프로젝트를 **zip으로 묶어서 업로드**",
					"- `README.md`로 프로젝트 개요 제공",
					"- `GPT.md`로 “AI에게 주는 개발 가이드”를 제공",
					"`GPT.md`에는 예를 들면 이런 걸 적어두었다.",
					"- 프로젝트 목표 / 주요 화면 구조",
					"- 데이터 흐름(상태/스토어/props) 규칙",
					"- 코딩 스타일 / 파일 분리 기준",
					"- 수정 시 “절대 건드리면 안 되는 부분”",
					"이건 결국 AI를 위한 문서이기도 했지만, 동시에 **나 자신을 위한 설계 문서**가 되기도 했다.",
					"---"
				]
			},
			{
				"heading": "결과 화면: “작동하는 편집기”까지 도달했다",
				"body": [
					"여러 시행착오 끝에, 실제로 편집기가 돌아가는 형태까지 만들 수 있었다. 아래 스크린샷이 그 결과다.",
					"![쇼츠 생성기 메인 화면](/posts/2026-09-01-shorts/20240901-shorts-editor-main-screenshot-01.png)",
					"완성도의 높고 낮음을 떠나서, 이 화면은 내게 꽤 상징적이었다.",
					"- AI가 만든 코드를 내가 조립했고",
					"- 내가 만든 제약과 규칙이 AI의 출력을 안정시켰고",
					"- 결국 “작동하는 도구”로 수렴했다",
					"---"
				]
			},
			{
				"heading": "수많은 AI와 수많은 챗이 남긴 것: 개발 감각과 ‘방향 잡는 법’",
				"body": [
					"가장 큰 수확은 기능 자체가 아니라, **AI와 개발하는 감각**이었다.",
					"그때 나는 수많은 AI와 수많은 챗을 반복하면서 이런 것들을 몸으로 익혔다.",
					"- 요구사항을 “기능”이 아니라 **상태 변화와 이벤트 흐름**으로 설명하기",
					"- 에러를 “에러 메시지”만 던지는 게 아니라 **재현 조건 + 기대 동작**까지 전달하기",
					"- 한 번에 크게 고치지 않고, **작은 단위로 안정적으로 전진하기**",
					"- AI가 생성한 코드를 그대로 믿지 않고, **테스트/검증 루프를 습관화**하기",
					"- 긴 코드보다 **작은 컴포넌트/유틸 단위**가 훨씬 잘 맞는다는 것",
					"그리고 무엇보다 확실히 알게 된 건 이거였다.",
					"> **AI는 누구에게나 비슷한 기능이 주어지지만, 결과는 비슷하지 않다.** > 결국 차이는, 같은 도구를 쓰더라도 > **목적을 잃지 않고 같은 방향을 보게 만들 수 있느냐**에서 생긴다.",
					"AI는 아주 똑똑하지만, 스스로 “왜 이걸 만드는지”를 끝까지 붙잡아주진 않는다. 중간에 흔들리고, 옆길로 새고, 그럴듯한 답을 내놓기도 한다.",
					"그래서 사람 쪽에서 해야 하는 일이 있다.",
					"- 목표를 계속 확인하고",
					"- 지금 수정이 목표에 부합하는지 점검하고",
					"- 중요한 기준(구조/규칙/흐름)을 문서와 코드로 고정해두고",
					"- 끝까지 목적을 향해 방향을 잡아주는 것",
					"이건 코드 스킬이라기보다, **개발을 끌고 가는 운영 능력**에 가까웠다.",
					"---"
				]
			},
			{
				"heading": "지금 시기의 AI 개발도 크게 다르지 않다: 그래서 더 도움이 됐다",
				"body": [
					"시간이 지나 지금은 모델도 도구도 훨씬 좋아졌지만, 아이러니하게도 **AI로 개발하는 핵심 패턴은 많이 비슷하다.**",
					"- 맥락은 여전히 관리해야 하고",
					"- 복잡한 기능일수록 작은 단위로 쪼개야 하고",
					"- 문서(가이드)로 의도를 고정해두면 정확도가 올라가고",
					"- 결국 사람의 역할은 “코딩”보다 **설계/검증/정리**에 가깝다",
					"그래서 이때 얻은 경험이 지금도 계속 도움이 된다. AI가 좋아질수록 더 빨리 만들 수는 있지만, **좋게 만드는 건 여전히 ‘사용법’의 영역**이다.",
					"---"
				]
			},
			{
				"heading": "마무리",
				"body": [
					"쇼츠 생성기 저작도구는 내게 단순한 개인 프로젝트가 아니라,",
					"- AI와 함께 개발하는 방식의 실험이었고",
					"- 대화 기반 개발의 한계를 체험한 기록이었고",
					"- 무엇보다 **보이지 않는 노하우를 축적한 시간**이었다",
					"2024년 9월 1일의 나는 이 프로젝트를 통해 AI와 함께 개발할 때 결국 중요한 것은 **기술 자체보다도, 끝까지 같은 목표를 바라보게 만드는 ‘방향 잡기’**라는 걸 배웠다.",
					"그리고 그 감각은 지금도 여전히 유효하다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-gangdongcamp",
		"title": "gangdongcamp 레포 스냅샷",
		"summary": "Go 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2023-06-10",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/gangdongcamp",
					"- Visibility: private",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2023-06-10 11:20:22 UTC",
					"- Last Push: 2023-07-09 06:25:27 UTC",
					"- Last Update: 2023-06-10 11:21:22 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-solquiz-server",
		"title": "solquiz-server 레포 스냅샷",
		"summary": "JavaScript 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2023-05-27",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/solquiz-server",
					"- Visibility: private",
					"- Primary Language: JavaScript",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2023-05-27 17:19:00 UTC",
					"- Last Push: 2023-05-28 13:59:51 UTC",
					"- Last Update: 2023-05-28 13:57:55 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-deploy-sh",
		"title": "deploy.sh 레포 스냅샷",
		"summary": "Shell 기반 공개 레포. The most convenient CI/CD in the world.",
		"date": "2023-05-04",
		"tags": [
			"devlog",
			"ops",
			"devops"
		],
		"category": "operations",
		"categoryName": "Operations",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/deploy.sh",
					"- Visibility: public",
					"- Primary Language: Shell",
					"- Homepage: (없음)",
					"- Description: The most convenient CI/CD in the world."
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2023-05-04 17:03:36 UTC",
					"- Last Push: 2026-02-14 09:00:51 UTC",
					"- Last Update: 2026-02-14 09:00:55 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- automation",
					"- cicd",
					"- continuous-delivery",
					"- continuous-integration",
					"- deploy",
					"- devops",
					"- kubernetes",
					"- bash",
					"- git"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "quizgame",
		"title": "퀴즈게임",
		"summary": "딸을 위한 퀴즈게임. 퀴즈들은 AI로 생성",
		"date": "2023-04-09",
		"tags": [
			"godot",
			"personal-site"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "/posts/2026-09-01-quizgame/quizgame-demo.mp4",
		"cardPoster": "/posts/2026-09-01-quizgame/quizgame-demo-poster.jpg",
		"bgVideoSrc": "/posts/2026-09-01-quizgame/quizgame-demo.mp4",
		"bgPoster": "/posts/2026-09-01-quizgame/quizgame-demo-poster.jpg",
		"content": [
			{
				"heading": "딸을 위해 만든 작은 퀴즈게임",
				"body": [
					"어느 날 문득, “딸이 좋아할 만한 게임을 하나 직접 만들어보자”는 마음이 들었다. 거창한 상업 프로젝트가 아니라 **정말로 ‘딸이 즐길 수 있는’** 작은 퀴즈게임.",
					"기술적으로는 Godot을 사용했고, 콘텐츠(문제)는 **AI 도움을 받아 빠르게 생성**했다. 결과적으로 이 프로젝트는 내게 두 가지 의미가 있었다.",
					"- **게임을 만들며 UI/리소스를 직접 다듬는 손맛**",
					"- **AI로 콘텐츠를 뽑아내며 느낀, 새로운 생산성의 충격**",
					"---"
				]
			},
			{
				"heading": "목표는 단순했다: “재미있고, 쉽게, 빨리”",
				"body": [
					"딸이 하는 게임인 만큼 기준도 명확했다.",
					"- 어렵지 않을 것 (아이 기준)",
					"- 텍스트가 너무 길지 않을 것",
					"- 틀려도 스트레스 받지 않을 것",
					"- 빠르게 다음 문제로 넘어갈 것",
					"- 무엇보다 “한 번만 하고 끝”이 아니라 **반복 플레이가 가능**할 것",
					"여기서 가장 큰 벽은 딱 하나였다.",
					"> **퀴즈 문제를 얼마나, 어떻게 만들 것인가?**",
					"게임 로직은 만들 수 있는데, 문제를 20개만 넣으면 금방 질린다. 그렇다고 사람이 수백 개를 손으로 만들기엔 시간이 너무 많이 든다.",
					"---"
				]
			},
			{
				"heading": "퀴즈는 AI로 생성: 수백 개를 “만들 수는 있었다”",
				"body": [
					"이 프로젝트에서 AI는 딱 한 역할에 집중했다.",
					"> **질문(퀴즈 문제) 생성**",
					"AI에게 요청하니 정말로 빠르게 수십 개, 수백 개의 질문이 나왔다. 이 속도는 당시(2023년 초중반 기준) 체감상 꽤 충격적이었다.",
					"- “이 주제로 퀴즈 30개 만들어줘”",
					"- “난이도 쉬움/보통 섞어줘”",
					"- “초등학생이 이해할 수 있게 바꿔줘”",
					"- “보기 4개, 정답 1개 형태로 만들어줘”",
					"이런 식으로 요청하면, 사람이 한참 걸려 만들 양을 **몇 분 안에 확보**할 수 있었다.",
					"---"
				]
			},
			{
				"heading": "현실의 벽: 이상한 질문, 중복되는 질문, 결국 사람 손이 필요했다",
				"body": [
					"AI가 많은 문제를 만들어준 건 사실인데, 그대로 게임에 넣기엔 문제가 있었다.",
					"- 뭔가 어색한 질문(표현이 이상하거나, 맥락이 이상함)",
					"- 사실관계가 애매한 질문(아이에게 오히려 혼란)",
					"- 중복되는 질문(표현만 다르고 내용은 같은 문제)",
					"- 난이도가 들쭉날쭉(아이 기준에서 갑자기 어려워지는 문제)",
					"결국 결론은 명확했다.",
					"> **생성은 AI가, 최종 편집은 사람이.**",
					"즉, “AI가 만들어 준 걸 그대로 쓰는 방식”이 아니라 **사람이 검수하고 다듬는 방식**이 필요했다.",
					"그래도 중요한 건, 사람이 해야 할 일이 “처음부터 끝까지 창작”이 아니라 **걸러내고 정리하는 일로 바뀌었다**는 점이었다.",
					"---"
				]
			},
			{
				"heading": "고민이 컸던 지점: “좋은 질문을 어떻게 뽑아내지?”",
				"body": [
					"처음엔 그냥 “퀴즈 만들어줘”로 시작했는데, 결과가 들쭉날쭉했다. 그래서 나름의 해결책을 만들었다.",
					"- 주제를 최대한 좁게 쪼개기 (예: 동물/음식/나라/과학상식…)",
					"- 질문 포맷을 고정하기 (문장 길이, 보기 개수, 정답 표기 규칙)",
					"- 금지 규칙을 먼저 주기 (너무 어려운 단어 금지, 함정 문제 금지)",
					"- 여러 번 생성해서 좋은 것만 채택하기 (샘플링 + 큐레이션)",
					"이 흐름을 잡고 나니까, “질문을 어떻게 만들지”에 대한 고민이 한 번에 깔끔하게 정리됐다.",
					"---"
				]
			},
			{
				"heading": "UI는 파워포인트로 만들었다: 그리고 그림을 쪼개서 구현",
				"body": [
					"이 프로젝트에서 UI 제작 방식도 꽤 아날로그(?)했다.",
					"- **파워포인트로 화면을 먼저 디자인**",
					"- 버튼/패널/배경 요소를 직접 만들고",
					"- 필요한 단위로 이미지를 **쪼개서** 리소스로 활용",
					"- Godot에 가져와 배치하며 실제 화면으로 조립",
					"즉, UI를 “코드로 먼저 만들기”보다 **눈으로 보이는 형태(PPT)로 먼저 확정하고 구현**하는 방식이었다.",
					"이 방식은 속도가 빨랐고, 무엇보다 “딸이 좋아할 만한 느낌”을 잡는 데 도움이 됐다. (게임 UI는 결국 감성의 영역이니까.)",
					"---"
				]
			},
			{
				"heading": "그때 느낀 생산성: 질문만 AI가 도와줘도 게임이 빨라졌다",
				"body": [
					"재밌었던 건, AI가 개발의 모든 걸 도와준 게 아니었다는 점이다.",
					"- 게임 로직: 내가 만들었다",
					"- UI/리소스: 내가 만들었다",
					"- 문제 생성: AI가 도와줬다",
					"그런데도 프로젝트 전체 진행 속도가 확 달라졌다. “콘텐츠 생산”이 병목인 프로젝트에서 AI는 특히 강력했다.",
					"그리고 그 순간 처음으로 확실히 느꼈다.",
					"> 게임과 AI를 조합하면, 만들 수 있는 게 정말 많아진다.",
					"---"
				]
			},
			{
				"heading": "게임과 AI의 조합은 무궁무진했다",
				"body": [
					"이 퀴즈게임은 작은 시작이었지만, 생각이 많이 확장됐다.",
					"- 플레이어 수준에 맞춰 난이도를 조절한다든지",
					"- 아이가 좋아하는 주제만 모아서 개인화한다든지",
					"- 매일 새로운 문제를 자동으로 추가한다든지",
					"- 대화형 NPC가 힌트를 준다든지",
					"“게임은 결국 콘텐츠”인데, 그 콘텐츠를 빠르게 만들 수 있다면 아이디어의 폭이 훨씬 넓어진다.",
					"---"
				]
			},
			{
				"heading": "플레이 링크",
				"body": [
					"게임은 여기서 플레이할 수 있다: `https://jjgo.itch.io/quiz`",
					"---"
				]
			},
			{
				"heading": "영상도 남겨뒀다",
				"body": [
					"이 프로젝트에는 영상이 두 개 있다.",
					"- 실행(플레이) 동영상 1개",
					"- 딸이 직접 플레이한 영상 1개",
					"<video controls playsinline preload=\"metadata\" src=\"/posts/2026-09-01-quizgame/quizgame-demo.mp4\"></video>",
					"<video controls playsinline preload=\"metadata\" src=\"/posts/2026-09-01-quizgame/quizgame-daughter-play.mp4\"></video>",
					"나중에 다시 보면, 완성도보다도 그 순간의 공기가 더 기억날 것 같다. “내가 만든 걸 딸이 직접 해본다”는 경험은 생각보다 특별했다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-solquiz",
		"title": "SolQuiz 레포 스냅샷",
		"summary": "GDScript 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2023-04-09",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/SolQuiz",
					"- Visibility: private",
					"- Primary Language: GDScript",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2023-04-09 06:52:40 UTC",
					"- Last Push: 2023-05-29 17:06:52 UTC",
					"- Last Update: 2023-04-09 06:56:13 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-todomd",
		"title": "todomd 레포 스냅샷",
		"summary": "Go 기반 공개 레포. A simple CLI tool to convert your Todo.md file into a CSV format that can be imported into Jira, written in Golang.",
		"date": "2023-04-02",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/todomd",
					"- Visibility: public",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: A simple CLI tool to convert your Todo.md file into a CSV format that can be imported into Jira, written in Golang."
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2023-04-02 14:11:28 UTC",
					"- Last Push: 2023-05-04 17:01:10 UTC",
					"- Last Update: 2026-02-19 14:10:49 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- jira",
					"- todo"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-projects",
		"title": "projects 레포 스냅샷",
		"summary": "기술 스택 미정 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2023-04-01",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/projects",
					"- Visibility: private",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2023-04-01 08:34:23 UTC",
					"- Last Push: 2023-04-06 12:00:38 UTC",
					"- Last Update: 2023-04-06 12:00:43 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-go-boilerplate-",
		"title": "go-boilerplate- 레포 스냅샷",
		"summary": "JavaScript 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2022-10-12",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/go-boilerplate-",
					"- Visibility: private",
					"- Primary Language: JavaScript",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2022-10-12 13:03:03 UTC",
					"- Last Push: 2022-10-12 13:03:50 UTC",
					"- Last Update: 2022-10-12 13:03:56 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-buss",
		"title": "buss 레포 스냅샷",
		"summary": "Go 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2022-01-17",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/buss",
					"- Visibility: private",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2022-01-17 20:58:57 UTC",
					"- Last Push: 2022-01-17 21:32:43 UTC",
					"- Last Update: 2022-01-17 21:02:12 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-nums",
		"title": "nums 레포 스냅샷",
		"summary": "GDScript 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2021-06-18",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/nums",
					"- Visibility: private",
					"- Primary Language: GDScript",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2021-06-18 16:28:09 UTC",
					"- Last Push: 2021-07-10 16:01:14 UTC",
					"- Last Update: 2021-07-10 16:01:17 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-keycloak-commento-sso",
		"title": "keycloak-commento-sso 레포 스냅샷",
		"summary": "Go 기반 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2021-03-06",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/keycloak-commento-sso",
					"- Visibility: public",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2021-03-06 16:47:25 UTC",
					"- Last Push: 2021-03-07 02:58:05 UTC",
					"- Last Update: 2021-03-07 02:58:07 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-sol",
		"title": "sol 레포 스냅샷",
		"summary": "JavaScript 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2020-09-26",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/sol",
					"- Visibility: private",
					"- Primary Language: JavaScript",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2020-09-26 11:19:38 UTC",
					"- Last Push: 2020-10-17 16:10:56 UTC",
					"- Last Update: 2020-10-17 16:10:58 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-myrancher",
		"title": "myrancher 레포 스냅샷",
		"summary": "Shell 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2019-05-27",
		"tags": [
			"devlog",
			"ops",
			"devops"
		],
		"category": "operations",
		"categoryName": "Operations",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/myrancher",
					"- Visibility: private",
					"- Primary Language: Shell",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2019-05-27 14:43:59 UTC",
					"- Last Push: 2019-05-27 14:46:23 UTC",
					"- Last Update: 2019-05-27 14:46:24 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-work-nas",
		"title": "work-nas 레포 스냅샷",
		"summary": "기술 스택 미정 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2019-05-01",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/work-nas",
					"- Visibility: private",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2019-05-01 14:45:56 UTC",
					"- Last Push: 2019-05-01 14:46:13 UTC",
					"- Last Update: 2019-05-01 14:56:33 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-awesome-check",
		"title": "awesome-check 레포 스냅샷",
		"summary": "Go 기반 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2019-03-29",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/awesome-check",
					"- Visibility: public",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2019-03-29 22:57:06 UTC",
					"- Last Push: 2019-04-01 16:17:21 UTC",
					"- Last Update: 2019-04-01 16:17:22 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-openvpn-dju",
		"title": "openvpn-dju 레포 스냅샷",
		"summary": "Shell 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2019-03-02",
		"tags": [
			"devlog",
			"ops",
			"devops"
		],
		"category": "operations",
		"categoryName": "Operations",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/openvpn-dju",
					"- Visibility: private",
					"- Primary Language: Shell",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2019-03-02 12:47:50 UTC",
					"- Last Push: 2019-03-03 09:46:18 UTC",
					"- Last Update: 2019-03-03 09:46:20 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-mass",
		"title": "mass 레포 스냅샷",
		"summary": "기술 스택 미정 비공개 레포. mass",
		"date": "2019-02-24",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/mass",
					"- Visibility: private",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: mass"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2019-02-24 07:50:32 UTC",
					"- Last Push: 2019-02-24 07:54:04 UTC",
					"- Last Update: 2019-02-24 07:54:06 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-main",
		"title": "main 레포 스냅샷",
		"summary": "Shell 기반 비공개 레포. Main",
		"date": "2019-02-07",
		"tags": [
			"devlog",
			"ops",
			"devops"
		],
		"category": "operations",
		"categoryName": "Operations",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/main",
					"- Visibility: private",
					"- Primary Language: Shell",
					"- Homepage: (없음)",
					"- Description: Main"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2019-02-07 15:13:31 UTC",
					"- Last Push: 2019-02-18 12:58:20 UTC",
					"- Last Update: 2019-02-18 12:58:21 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-readme-for-projects",
		"title": "readme-for-projects 레포 스냅샷",
		"summary": "Shell 기반 공개 레포. Generate readme for info of projects",
		"date": "2019-02-07",
		"tags": [
			"devlog",
			"ops",
			"devops"
		],
		"category": "operations",
		"categoryName": "Operations",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/readme-for-projects",
					"- Visibility: public",
					"- Primary Language: Shell",
					"- Homepage: (없음)",
					"- Description: Generate readme for info of projects"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2019-02-07 15:37:04 UTC",
					"- Last Push: 2019-02-18 12:12:02 UTC",
					"- Last Update: 2019-02-18 12:12:04 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-katacoda-scenarios",
		"title": "katacoda-scenarios 레포 스냅샷",
		"summary": "기술 스택 미정 공개 레포. Katacoda Scenarios",
		"date": "2019-01-20",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/katacoda-scenarios",
					"- Visibility: public",
					"- Primary Language: N/A",
					"- Homepage: https://www.katacoda.com/jjgo",
					"- Description: Katacoda Scenarios"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2019-01-20 11:20:00 UTC",
					"- Last Push: 2019-01-20 11:20:05 UTC",
					"- Last Update: 2019-01-20 11:20:06 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-rancher-install",
		"title": "rancher-install 레포 스냅샷",
		"summary": "기술 스택 미정 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2019-01-12",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/rancher-install",
					"- Visibility: public",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2019-01-12 13:20:02 UTC",
					"- Last Push: 2019-01-12 13:20:03 UTC",
					"- Last Update: 2019-01-12 13:20:02 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-blog",
		"title": "blog 레포 스냅샷",
		"summary": "Shell 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2018-12-27",
		"tags": [
			"devlog",
			"ops",
			"devops"
		],
		"category": "operations",
		"categoryName": "Operations",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/blog",
					"- Visibility: private",
					"- Primary Language: Shell",
					"- Homepage: https://jungju.github.io/",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-12-27 12:02:08 UTC",
					"- Last Push: 2019-01-19 08:18:54 UTC",
					"- Last Update: 2019-01-19 08:18:56 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-jungju-github-io",
		"title": "jungju.github.io 레포 스냅샷",
		"summary": "HTML 기반 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2018-12-27",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/jungju.github.io",
					"- Visibility: public",
					"- Primary Language: HTML",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-12-27 14:09:56 UTC",
					"- Last Push: 2018-12-27 14:16:30 UTC",
					"- Last Update: 2018-12-27 14:16:31 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-study-english",
		"title": "study_english 레포 스냅샷",
		"summary": "기술 스택 미정 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2018-12-27",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/study_english",
					"- Visibility: private",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-12-27 09:46:17 UTC",
					"- Last Push: 2019-01-01 05:58:52 UTC",
					"- Last Update: 2019-01-01 05:58:53 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-awesome-english",
		"title": "awesome-english 레포 스냅샷",
		"summary": "기술 스택 미정 공개 레포. 영어 공부 for 영어 포기자들",
		"date": "2018-11-02",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/awesome-english",
					"- Visibility: public",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: 영어 공부 for 영어 포기자들"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-11-02 02:52:43 UTC",
					"- Last Push: 2018-11-12 15:24:56 UTC",
					"- Last Update: 2018-11-12 15:24:57 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-heyeng",
		"title": "heyeng 레포 스냅샷",
		"summary": "기술 스택 미정 공개 레포. Microsoft Gadget(2006 Gadgets Contest)",
		"date": "2018-10-07",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/heyeng",
					"- Visibility: public",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: Microsoft Gadget(2006 Gadgets Contest)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-10-07 13:57:46 UTC",
					"- Last Push: 2018-10-07 14:04:48 UTC",
					"- Last Update: 2018-10-07 14:04:49 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-awesome-jeju",
		"title": "awesome-jeju 레포 스냅샷",
		"summary": "기술 스택 미정 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2018-10-06",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/awesome-jeju",
					"- Visibility: public",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-10-06 15:25:07 UTC",
					"- Last Push: 2018-10-06 15:27:55 UTC",
					"- Last Update: 2018-10-06 15:27:56 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-aha",
		"title": "aha 레포 스냅샷",
		"summary": "JavaScript 기반 공개 레포. 3D diagram authoring tool",
		"date": "2018-10-05",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/aha",
					"- Visibility: public",
					"- Primary Language: JavaScript",
					"- Homepage: (없음)",
					"- Description: 3D diagram authoring tool"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-10-05 15:20:28 UTC",
					"- Last Push: 2018-10-05 15:26:29 UTC",
					"- Last Update: 2023-01-28 19:55:31 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- threejs"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-greensmoke",
		"title": "greensmoke 레포 스냅샷",
		"summary": "C# 기반 공개 레포. Remote and mode control of power-line based electronic devices",
		"date": "2018-09-25",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/greensmoke",
					"- Visibility: public",
					"- Primary Language: C#",
					"- Homepage: (없음)",
					"- Description: Remote and mode control of power-line based electronic devices"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-09-25 08:29:56 UTC",
					"- Last Push: 2018-09-25 09:21:26 UTC",
					"- Last Update: 2023-01-28 19:55:35 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-idea-helper",
		"title": "idea_helper 레포 스냅샷",
		"summary": "C# 기반 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2018-09-25",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/idea_helper",
					"- Visibility: public",
					"- Primary Language: C#",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-09-25 08:55:32 UTC",
					"- Last Push: 2018-09-25 09:17:22 UTC",
					"- Last Update: 2023-01-28 19:55:35 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-timelapsemaker",
		"title": "TimelapseMaker 레포 스냅샷",
		"summary": "C# 기반 공개 레포. Convert Time-Lapse images to high-quality images",
		"date": "2018-09-25",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/TimelapseMaker",
					"- Visibility: public",
					"- Primary Language: C#",
					"- Homepage: (없음)",
					"- Description: Convert Time-Lapse images to high-quality images"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-09-25 08:17:33 UTC",
					"- Last Push: 2018-10-05 16:06:39 UTC",
					"- Last Update: 2024-01-12 09:27:28 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- timelapse"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-tiny-server",
		"title": "tiny-server 레포 스냅샷",
		"summary": "Shell 기반 공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2018-09-25",
		"tags": [
			"devlog",
			"ops",
			"devops"
		],
		"category": "operations",
		"categoryName": "Operations",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/tiny-server",
					"- Visibility: public",
					"- Primary Language: Shell",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-09-25 13:38:23 UTC",
					"- Last Push: 2018-09-25 13:57:33 UTC",
					"- Last Update: 2018-09-25 13:57:35 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- server"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-gorancher",
		"title": "gorancher 레포 스냅샷",
		"summary": "Go 기반 비공개 레포. rancher2 client golang",
		"date": "2018-06-26",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/gorancher",
					"- Visibility: private",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: rancher2 client golang"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-06-26 08:25:55 UTC",
					"- Last Push: 2018-07-27 12:11:31 UTC",
					"- Last Update: 2018-11-10 07:52:29 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- rancher",
					"- golang"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-gorm-adapter",
		"title": "gorm-adapter 레포 스냅샷",
		"summary": "Go 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2018-06-18",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/gorm-adapter",
					"- Visibility: private",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-06-18 11:32:59 UTC",
					"- Last Push: 2018-06-18 11:39:05 UTC",
					"- Last Update: 2018-11-10 07:50:55 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-circle-manager",
		"title": "circle_manager 레포 스냅샷",
		"summary": "Go 기반 비공개 레포. Codeless API/Admin/Swagger Creator",
		"date": "2018-04-12",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/circle_manager",
					"- Visibility: private",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: Codeless API/Admin/Swagger Creator"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-04-12 15:02:19 UTC",
					"- Last Push: 2018-10-23 09:14:41 UTC",
					"- Last Update: 2018-11-10 07:33:11 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- beego",
					"- golang",
					"- gorm",
					"- qor"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-circle",
		"title": "circle 레포 스냅샷",
		"summary": "JavaScript 기반 비공개 레포. circle",
		"date": "2018-03-05",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/circle",
					"- Visibility: private",
					"- Primary Language: JavaScript",
					"- Homepage: (없음)",
					"- Description: circle"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-03-05 06:17:12 UTC",
					"- Last Push: 2018-12-24 14:56:24 UTC",
					"- Last Update: 2018-12-24 14:56:26 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-brainstorming",
		"title": "brainstorming 레포 스냅샷",
		"summary": "기술 스택 미정 비공개 레포. 생각해보자",
		"date": "2018-02-10",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/brainstorming",
					"- Visibility: private",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: 생각해보자"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2018-02-10 17:42:07 UTC",
					"- Last Push: 2018-02-10 18:16:48 UTC",
					"- Last Update: 2018-02-10 17:43:07 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-cloud9-docker",
		"title": "cloud9-docker 레포 스냅샷",
		"summary": "Go 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2017-12-11",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/cloud9-docker",
					"- Visibility: private",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-12-11 02:47:21 UTC",
					"- Last Push: 2018-02-11 15:20:22 UTC",
					"- Last Update: 2018-11-10 07:58:27 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-allpos",
		"title": "allpos 레포 스냅샷",
		"summary": "PHP 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2017-11-18",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/allpos",
					"- Visibility: private",
					"- Primary Language: PHP",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-11-18 15:07:32 UTC",
					"- Last Push: 2017-11-18 15:08:03 UTC",
					"- Last Update: 2017-11-18 15:08:06 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-ass3",
		"title": "ass3 레포 스냅샷",
		"summary": "PHP 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2017-11-18",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/ass3",
					"- Visibility: private",
					"- Primary Language: PHP",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-11-18 15:08:34 UTC",
					"- Last Push: 2017-11-18 15:09:21 UTC",
					"- Last Update: 2017-11-18 15:09:23 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-ass4",
		"title": "ass4 레포 스냅샷",
		"summary": "PHP 기반 비공개 레포. ass4",
		"date": "2017-11-18",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/ass4",
					"- Visibility: private",
					"- Primary Language: PHP",
					"- Homepage: (없음)",
					"- Description: ass4"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-11-18 15:09:39 UTC",
					"- Last Push: 2017-11-18 16:23:09 UTC",
					"- Last Update: 2017-11-18 15:10:30 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-awesome-idea",
		"title": "awesome-idea 레포 스냅샷",
		"summary": "기술 스택 미정 비공개 레포. 나의 아이디어 모음",
		"date": "2017-10-28",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/awesome-idea",
					"- Visibility: private",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: 나의 아이디어 모음"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-10-28 15:49:13 UTC",
					"- Last Push: 2017-10-28 16:05:40 UTC",
					"- Last Update: 2017-10-28 15:49:13 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-gorm-manager",
		"title": "gorm_manager 레포 스냅샷",
		"summary": "Go 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2017-09-22",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/gorm_manager",
					"- Visibility: private",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-09-22 01:27:00 UTC",
					"- Last Push: 2018-06-25 14:51:27 UTC",
					"- Last Update: 2018-11-10 07:49:49 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-qor-admin-auth",
		"title": "qor_admin_auth 레포 스냅샷",
		"summary": "Go 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2017-09-21",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/qor_admin_auth",
					"- Visibility: private",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-09-21 16:22:45 UTC",
					"- Last Push: 2018-09-04 04:26:36 UTC",
					"- Last Update: 2018-11-10 07:51:48 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-ass-auth-theme",
		"title": "ass_auth_theme 레포 스냅샷",
		"summary": "Go 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2017-09-20",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/ass_auth_theme",
					"- Visibility: private",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-09-20 06:04:28 UTC",
					"- Last Push: 2017-09-20 06:06:22 UTC",
					"- Last Update: 2017-09-20 06:06:25 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-ahg",
		"title": "ahg 레포 스냅샷",
		"summary": "Go 기반 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2017-09-14",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/ahg",
					"- Visibility: private",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-09-14 13:40:25 UTC",
					"- Last Push: 2017-09-14 13:41:07 UTC",
					"- Last Update: 2017-09-14 13:41:13 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-lifelog",
		"title": "lifelog 레포 스냅샷",
		"summary": "Go 기반 공개 레포. Let's collect all the events",
		"date": "2017-09-14",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/lifelog",
					"- Visibility: public",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: Let's collect all the events"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-09-14 13:42:35 UTC",
					"- Last Push: 2018-10-05 14:56:16 UTC",
					"- Last Update: 2023-01-28 19:55:32 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- jawbone",
					"- iot",
					"- healthcare"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-ass-old",
		"title": "ass-old 레포 스냅샷",
		"summary": "HTML 기반 비공개 레포. deprecated",
		"date": "2017-09-09",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/ass-old",
					"- Visibility: private",
					"- Primary Language: HTML",
					"- Homepage: (없음)",
					"- Description: deprecated"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-09-09 15:28:07 UTC",
					"- Last Push: 2017-11-18 15:18:14 UTC",
					"- Last Update: 2017-11-05 16:12:07 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-dju-grad",
		"title": "dju-grad 레포 스냅샷",
		"summary": "기술 스택 미정 비공개 레포 스냅샷과 작업 맥락 정리.",
		"date": "2017-09-09",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/dju-grad",
					"- Visibility: private",
					"- Primary Language: N/A",
					"- Homepage: (없음)",
					"- Description: (설명 없음)"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-09-09 15:45:49 UTC",
					"- Last Push: 2017-09-09 15:46:36 UTC",
					"- Last Update: 2017-09-09 15:45:49 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-swagview",
		"title": "swagview 레포 스냅샷",
		"summary": "Go 기반 비공개 레포. swagger to admin",
		"date": "2017-07-24",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/swagview",
					"- Visibility: private",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: swagger to admin"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-07-24 04:52:59 UTC",
					"- Last Push: 2017-09-14 10:37:32 UTC",
					"- Last Update: 2023-01-28 19:55:29 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- generator",
					"- admin",
					"- beego"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-malhagi",
		"title": "malhagi 레포 스냅샷",
		"summary": "Go 기반 공개 레포. 영어 말하기 연습 게임",
		"date": "2017-06-07",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/malhagi",
					"- Visibility: public",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: 영어 말하기 연습 게임"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2017-06-07 16:24:33 UTC",
					"- Last Push: 2017-06-11 12:46:49 UTC",
					"- Last Update: 2017-10-28 15:44:59 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-apit",
		"title": "apit 레포 스냅샷",
		"summary": "Go 기반 공개 레포. Go tesing tool base gin",
		"date": "2016-03-10",
		"tags": [
			"devlog"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/apit",
					"- Visibility: public",
					"- Primary Language: Go",
					"- Homepage: (없음)",
					"- Description: Go tesing tool base gin"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2016-03-10 04:58:10 UTC",
					"- Last Push: 2016-04-06 13:32:14 UTC",
					"- Last Update: 2023-01-28 19:55:28 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-environment",
		"title": "environment 레포 스냅샷",
		"summary": "Shell 기반 공개 레포. Environment for develop.",
		"date": "2015-11-16",
		"tags": [
			"devlog",
			"ops",
			"devops"
		],
		"category": "operations",
		"categoryName": "Operations",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/environment",
					"- Visibility: public",
					"- Primary Language: Shell",
					"- Homepage: (없음)",
					"- Description: Environment for develop."
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2015-11-16 04:53:17 UTC",
					"- Last Push: 2016-02-03 14:42:33 UTC",
					"- Last Update: 2016-01-30 16:20:35 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- (없음)"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "repo-dosisa",
		"title": "Dosisa 레포 스냅샷",
		"summary": "HTML 기반 공개 레포. Simulation to be careful of mistakes",
		"date": "2014-06-18",
		"tags": [
			"devlog",
			"frontend"
		],
		"category": "development",
		"categoryName": "Development",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "개요",
				"body": [
					"- Repository: https://github.com/jungju/Dosisa",
					"- Visibility: public",
					"- Primary Language: HTML",
					"- Homepage: (없음)",
					"- Description: Simulation to be careful of mistakes"
				]
			},
			{
				"heading": "메타데이터",
				"body": [
					"- Created: 2014-06-18 17:28:40 UTC",
					"- Last Push: 2018-10-06 12:35:29 UTC",
					"- Last Update: 2023-01-28 19:55:15 UTC"
				]
			},
			{
				"heading": "Topics",
				"body": [
					"- hackathon",
					"- parody"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 이 글은 github.com/jungju 계정의 직접 생성 레포를 일괄 스캔해 자동 생성한 기록이다.",
					"- 세부 구현/회고는 이후 커밋 단위로 보강한다."
				]
			}
		],
		"links": []
	}
];
export const generatedMeta = {
	"tags": [
		{
			"id": "a11y",
			"name": "Accessibility",
			"description": "접근성 개선",
			"color": "#10b981",
			"count": 1
		},
		{
			"id": "automation",
			"name": "Automation",
			"description": "자동화 작업",
			"color": "#84cc16",
			"count": 1
		},
		{
			"id": "ci-cd",
			"name": "CI/CD",
			"description": "지속적 통합/배포",
			"color": "#06b6d4",
			"count": 1
		},
		{
			"id": "devlog",
			"name": "Devlog",
			"description": "개발 과정과 회고 기록",
			"color": "#38bdf8",
			"count": 63
		},
		{
			"id": "devops",
			"name": "DevOps",
			"description": "개발/운영 통합",
			"color": "#0284c7",
			"count": 10
		},
		{
			"id": "elevenlabs",
			"name": "elevenlabs",
			"description": "",
			"color": "",
			"count": 1
		},
		{
			"id": "english-study",
			"name": "english-study",
			"description": "",
			"color": "",
			"count": 1
		},
		{
			"id": "eval",
			"name": "Evaluation",
			"description": "평가 지표 및 실험",
			"color": "#0ea5e9",
			"count": 1
		},
		{
			"id": "frontend",
			"name": "Frontend",
			"description": "프론트엔드 구현",
			"color": "#3b82f6",
			"count": 14
		},
		{
			"id": "godot",
			"name": "godot",
			"description": "",
			"color": "",
			"count": 1
		},
		{
			"id": "gpt",
			"name": "gpt",
			"description": "",
			"color": "",
			"count": 1
		},
		{
			"id": "incident",
			"name": "Incident",
			"description": "장애 대응 기록",
			"color": "#ef4444",
			"count": 1
		},
		{
			"id": "ops",
			"name": "Ops",
			"description": "운영 및 배포",
			"color": "#f59e0b",
			"count": 10
		},
		{
			"id": "performance",
			"name": "Performance",
			"description": "성능 개선 및 병목 분석",
			"color": "#14b8a6",
			"count": 1
		},
		{
			"id": "personal-site",
			"name": "Personal Site",
			"description": "개인 사이트 구축 관련",
			"color": "#22c55e",
			"count": 3
		},
		{
			"id": "postmortem",
			"name": "Postmortem",
			"description": "장애 사후 분석",
			"color": "#dc2626",
			"count": 1
		},
		{
			"id": "prompt",
			"name": "Prompt",
			"description": "프롬프트 설계",
			"color": "#6366f1",
			"count": 1
		},
		{
			"id": "quality",
			"name": "Quality",
			"description": "품질 관리",
			"color": "#22c55e",
			"count": 1
		},
		{
			"id": "rag",
			"name": "RAG",
			"description": "검색증강생성 아키텍처",
			"color": "#0ea5e9",
			"count": 1
		},
		{
			"id": "react",
			"name": "react",
			"description": "",
			"color": "",
			"count": 1
		},
		{
			"id": "retrospective",
			"name": "Retrospective",
			"description": "회고와 교훈 정리",
			"color": "#8b5cf6",
			"count": 1
		},
		{
			"id": "svelte",
			"name": "Svelte",
			"description": "Svelte 컴포넌트 작업",
			"color": "#f43f5e",
			"count": 1
		},
		{
			"id": "sveltekit",
			"name": "SvelteKit",
			"description": "SvelteKit 관련 구현 기록",
			"color": "#f97316",
			"count": 0
		}
	],
	"categories": [
		{
			"id": "development",
			"name": "Development",
			"description": "개발 구현, 개선, 리팩토링 중심 기록",
			"count": 60
		},
		{
			"id": "operations",
			"name": "Operations",
			"description": "운영, 장애 대응, 배포 관련 기록",
			"count": 10
		},
		{
			"id": "research",
			"name": "Research",
			"description": "실험, 검증, 학습 노트",
			"count": 1
		}
	]
};

