// Auto-generated by scripts/sync-content-to-src.mjs
// Do not edit this file directly.

export const generatedStories = [
	{
		"slug": "first-dev-log",
		"title": "첫 개발기: 내 기록 시스템 시작",
		"summary": "개인 개발 아카이브 사이트의 첫 구조를 잡고, 기록 흐름을 정리한 날.",
		"date": "2026-02-12",
		"tags": [
			"devlog",
			"sveltekit",
			"personal-site"
		],
		"category": "development",
		"categoryName": "Development",
		"series": "build-my-archive",
		"seriesName": "Build My Archive",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "본문",
				"body": [
					"오늘은 개인 개발 아카이브 사이트의 뼈대를 만들었다. 목표는 단순하다.",
					"1. 개발기는 빠르게 남긴다.",
					"2. 생각은 짧게라도 기록한다.",
					"3. 다시 찾기 쉽게 정리한다."
				]
			},
			{
				"heading": "오늘 한 일",
				"body": [
					"- `SPEC/` 기준으로 프로젝트 목적과 룰 정리",
					"- `content/` 아래 글/사진/영상 폴더 구조 분리",
					"- 게시글 파일 네이밍 규칙 확정 (`YYYY-MM-DD-title.md`)"
				]
			},
			{
				"heading": "왜 이렇게 했는가",
				"body": [
					"예전에는 글과 파일이 흩어져서 기록이 쌓일수록 찾기 어려웠다. 이번에는 처음부터 구조를 고정해서, 작성과 관리 비용을 줄이는 데 집중했다."
				]
			},
			{
				"heading": "다음 작업",
				"body": [
					"1. `content/posts/published/` 글 목록을 홈 화면에 연결",
					"2. 태그 기반 필터 추가",
					"3. 썸네일/영상 메타와 게시글 연동"
				]
			},
			{
				"heading": "한 줄 회고",
				"body": [
					"시작은 작게, 구조는 단단하게."
				]
			}
		],
		"links": []
	},
	{
		"slug": "rag-latency-retro",
		"title": "RAG 지연 줄이기 회고",
		"summary": "검색과 직렬화 병목을 분리해서 응답 지연을 줄인 과정 정리.",
		"date": "2026-02-11",
		"tags": [
			"rag",
			"performance",
			"retrospective"
		],
		"category": "development",
		"categoryName": "Development",
		"series": "latency-lab",
		"seriesName": "Latency Lab",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "본문",
				"body": [
					"검색 품질은 괜찮았지만 응답 시작이 느렸다. 이번 글은 병목을 잘라서 본 과정 기록이다."
				]
			},
			{
				"heading": "문제",
				"body": [
					"- 사용자는 정답률보다 첫 응답 속도에 더 민감했다.",
					"- 같은 질문이 반복되는데도 캐시 적중률이 낮았다."
				]
			},
			{
				"heading": "조치",
				"body": [
					"1. 전처리 직렬화 단계를 경량 포맷으로 교체",
					"2. 상위 반복 질의를 메모리 캐시에 고정",
					"3. 응답 스트리밍 시작 시점을 앞당김"
				]
			},
			{
				"heading": "결과",
				"body": [
					"- 체감 응답 속도 개선",
					"- 재시도율 감소",
					"- 회귀 확인용 지표를 대시보드에 추가"
				]
			},
			{
				"heading": "다음",
				"body": [
					"- 질문 유형별 캐시 전략 분리",
					"- 주간 회귀 리포트 자동화"
				]
			}
		],
		"links": []
	},
	{
		"slug": "ui-a11y-fix-log",
		"title": "UI 접근성 수정 로그",
		"summary": "키보드 접근성과 클릭 가능한 정적 요소 문제를 정리하고 수정한 기록.",
		"date": "2026-02-10",
		"tags": [
			"frontend",
			"a11y",
			"svelte"
		],
		"category": "development",
		"categoryName": "Development",
		"series": "ui-quality",
		"seriesName": "UI Quality",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "본문",
				"body": [
					"체크 도구 경고를 쌓아두면 나중에 고치기 더 어렵다. 작게 나눠서 바로바로 수정했다."
				]
			},
			{
				"heading": "발견",
				"body": [
					"- 클릭 이벤트가 있는 비상호작용 요소 존재",
					"- 이미지 alt 누락",
					"- 자기닫힘 태그 사용으로 마크업 경고 발생"
				]
			},
			{
				"heading": "수정",
				"body": [
					"1. `div` 클릭 UI를 버튼/링크로 교체",
					"2. 이미지에 의미 있는 alt 추가",
					"3. `audio` 태그를 명시적 닫힘 태그로 변경"
				]
			},
			{
				"heading": "메모",
				"body": [
					"- 기능보다 사용성 기본기부터 유지",
					"- 경고 1개라도 PR 전에 정리"
				]
			}
		],
		"links": []
	},
	{
		"slug": "prod-incident-001",
		"title": "장애 기록 #001 - 정적 파일 경로 이슈",
		"summary": "배포 후 일부 페이지의 정적 리소스 경로가 깨진 장애와 복구 과정.",
		"date": "2026-02-09",
		"tags": [
			"incident",
			"ops",
			"postmortem"
		],
		"category": "operations",
		"categoryName": "Operations",
		"series": "incident-log",
		"seriesName": "Incident Log",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "본문",
				"body": [
					"배포 직후 일부 브라우저에서 포스터 이미지가 로드되지 않았다. 원인은 단순했지만 발견까지 시간이 걸렸다."
				]
			},
			{
				"heading": "영향",
				"body": [
					"- 카드 썸네일 일부 미노출",
					"- 상세 페이지 배경 포스터 폴백 실패"
				]
			},
			{
				"heading": "원인",
				"body": [
					"1. 상대 경로와 base 경로 혼용",
					"2. 환경별 경로 접두어 누락"
				]
			},
			{
				"heading": "조치",
				"body": [
					"- 모든 정적 자산 경로 규칙 통일",
					"- 배포 후 체크리스트에 리소스 로드 점검 추가"
				]
			},
			{
				"heading": "회고",
				"body": [
					"- \"작은 경로 차이\"가 장애로 이어진다.",
					"- 복구보다 사전 검증 자동화가 비용이 낮다."
				]
			}
		],
		"links": []
	},
	{
		"slug": "ci-cd-small-wins",
		"title": "CI/CD 소소한 개선 모음",
		"summary": "작지만 반복되는 배포 불편을 줄인 자동화 개선 목록.",
		"date": "2026-02-08",
		"tags": [
			"ci-cd",
			"automation",
			"devops"
		],
		"category": "development",
		"categoryName": "Development",
		"series": "small-wins",
		"seriesName": "Small Wins",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "본문",
				"body": [
					"큰 리팩토링보다 작은 자동화가 팀 시간을 더 많이 절약할 때가 많다. 이번 주는 그 작은 개선에 집중했다."
				]
			},
			{
				"heading": "적용한 것",
				"body": [
					"- 빌드 전 콘텐츠 동기화(`make content`)를 파이프라인에 강제",
					"- 실패 로그에서 핵심 에러 라인만 먼저 노출",
					"- 배포 전 체크 타임아웃과 재시도 정책 조정"
				]
			},
			{
				"heading": "효과",
				"body": [
					"1. 배포 전 누락 이슈 감소",
					"2. 실패 원인 확인 시간 단축",
					"3. 수동 확인 단계 축소"
				]
			},
			{
				"heading": "다음 주 계획",
				"body": [
					"- 체크 결과를 슬랙 요약 메시지로 발송",
					"- 릴리즈 노트 자동 생성 실험"
				]
			}
		],
		"links": []
	},
	{
		"slug": "prompt-eval-weekly",
		"title": "Prompt Eval 주간 노트1",
		"summary": "프롬프트 변경이 품질 지표에 미친 영향을 주간 단위로 기록.",
		"date": "2026-02-07",
		"tags": [
			"prompt",
			"eval",
			"quality"
		],
		"category": "research",
		"categoryName": "Research",
		"series": "prompt-ops",
		"seriesName": "Prompt Ops",
		"cardVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"cardPoster": "/posters/story-card.svg",
		"bgVideoSrc": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
		"bgPoster": "/posters/story-bg.svg",
		"content": [
			{
				"heading": "본문",
				"body": [
					"프롬프트는 작은 문장 차이로 결과가 크게 달라진다. 이번 주는 변경 이력과 평가를 같이 봤다."
				]
			},
			{
				"heading": "이번 주 변경",
				"body": [
					"1. 역할 지시 문장을 짧게 정리",
					"2. 출력 포맷 제약을 명확화",
					"3. 금지 표현 목록을 시스템 프롬프트로 이동"
				]
			},
			{
				"heading": "관찰",
				"body": [
					"- 길이 제약을 명확히 할수록 응답 일관성이 올라갔다.",
					"- 과한 제약은 설명력 저하로 이어졌다."
				]
			},
			{
				"heading": "결론",
				"body": [
					"- \"짧고 명확한 지시 + 최소 제약\"이 현재 데이터셋에서 가장 안정적이었다."
				]
			},
			{
				"heading": "액션",
				"body": [
					"- 실패 케이스를 유형별로 태깅",
					"- 다음 주에는 회귀 케이스 비율을 지표로 추가"
				]
			}
		],
		"links": []
	}
];
export const generatedMeta = {
	"tags": [
		{
			"id": "a11y",
			"name": "Accessibility",
			"description": "접근성 개선",
			"color": "#10b981",
			"count": 1
		},
		{
			"id": "automation",
			"name": "Automation",
			"description": "자동화 작업",
			"color": "#84cc16",
			"count": 1
		},
		{
			"id": "ci-cd",
			"name": "CI/CD",
			"description": "지속적 통합/배포",
			"color": "#06b6d4",
			"count": 1
		},
		{
			"id": "devlog",
			"name": "Devlog",
			"description": "개발 과정과 회고 기록",
			"color": "#38bdf8",
			"count": 1
		},
		{
			"id": "devops",
			"name": "DevOps",
			"description": "개발/운영 통합",
			"color": "#0284c7",
			"count": 1
		},
		{
			"id": "eval",
			"name": "Evaluation",
			"description": "평가 지표 및 실험",
			"color": "#0ea5e9",
			"count": 1
		},
		{
			"id": "frontend",
			"name": "Frontend",
			"description": "프론트엔드 구현",
			"color": "#3b82f6",
			"count": 1
		},
		{
			"id": "incident",
			"name": "Incident",
			"description": "장애 대응 기록",
			"color": "#ef4444",
			"count": 1
		},
		{
			"id": "ops",
			"name": "Ops",
			"description": "운영 및 배포",
			"color": "#f59e0b",
			"count": 1
		},
		{
			"id": "performance",
			"name": "Performance",
			"description": "성능 개선 및 병목 분석",
			"color": "#14b8a6",
			"count": 1
		},
		{
			"id": "personal-site",
			"name": "Personal Site",
			"description": "개인 사이트 구축 관련",
			"color": "#22c55e",
			"count": 1
		},
		{
			"id": "postmortem",
			"name": "Postmortem",
			"description": "장애 사후 분석",
			"color": "#dc2626",
			"count": 1
		},
		{
			"id": "prompt",
			"name": "Prompt",
			"description": "프롬프트 설계",
			"color": "#6366f1",
			"count": 1
		},
		{
			"id": "quality",
			"name": "Quality",
			"description": "품질 관리",
			"color": "#22c55e",
			"count": 1
		},
		{
			"id": "rag",
			"name": "RAG",
			"description": "검색증강생성 아키텍처",
			"color": "#0ea5e9",
			"count": 1
		},
		{
			"id": "retrospective",
			"name": "Retrospective",
			"description": "회고와 교훈 정리",
			"color": "#8b5cf6",
			"count": 1
		},
		{
			"id": "svelte",
			"name": "Svelte",
			"description": "Svelte 컴포넌트 작업",
			"color": "#f43f5e",
			"count": 1
		},
		{
			"id": "sveltekit",
			"name": "SvelteKit",
			"description": "SvelteKit 관련 구현 기록",
			"color": "#f97316",
			"count": 1
		}
	],
	"categories": [
		{
			"id": "development",
			"name": "Development",
			"description": "개발 구현, 개선, 리팩토링 중심 기록",
			"count": 4
		},
		{
			"id": "operations",
			"name": "Operations",
			"description": "운영, 장애 대응, 배포 관련 기록",
			"count": 1
		},
		{
			"id": "research",
			"name": "Research",
			"description": "실험, 검증, 학습 노트",
			"count": 1
		}
	],
	"series": [
		{
			"id": "build-my-archive",
			"name": "Build My Archive",
			"description": "개인 아카이브 사이트 구축 시리즈",
			"count": 1
		},
		{
			"id": "incident-log",
			"name": "Incident Log",
			"description": "장애 대응 기록 시리즈",
			"count": 1
		},
		{
			"id": "latency-lab",
			"name": "Latency Lab",
			"description": "지연 최적화 실험 시리즈",
			"count": 1
		},
		{
			"id": "prompt-ops",
			"name": "Prompt Ops",
			"description": "프롬프트 운영 실험 시리즈",
			"count": 1
		},
		{
			"id": "small-wins",
			"name": "Small Wins",
			"description": "작은 개선 모음 시리즈",
			"count": 1
		},
		{
			"id": "ui-quality",
			"name": "UI Quality",
			"description": "UI/UX 품질 개선 시리즈",
			"count": 1
		}
	]
};

